### ISSUE TITLE
Odroid C2 - Is it 32bit Userspace?

### ISSUE THREAD

**Issue by matthuisman** [CoreELEC/CoreELEC#108]
Couldn't find any info.

Just wanted to make sure the Odroid C2 builds are using 32bit userspace so I can playback Widevine content?

Currently I use Raybuntu LibreELEC 32bit.

I see Raybuntu is a contributor to this project, so I suspect the answer will be yes.

**Comment by adamg88** [comment]
The answer is in the filenames 'ARM' vs 'aarch64'.

**Comment by matthuisman** [comment]
Oh, sorry!
Thanks :D
