### ISSUE TITLE
MPEG2 decoding errors and freezes.

### ISSUE THREAD

**Issue by azidman** [CoreELEC/CoreELEC#109]
When i view mpeg2 sd channels via dvbviewer Client i get a bad frame every 10-90 minutes.
Every 24-36 hours the box completely freezes and shows a grey or brown screen often also with small audio samples looped.
Then i have to repower the box.

Other people on german kodinerds forum confirmed this:
https://www.kodinerds.net/index.php/Thread/53825-CoreELEC-Amlogic-Rockchip/?postID=464075#post464075

in my opinion the log says nothing but here it is:
[log-2018-06-07-03.09.13.zip](https://github.com/CoreELEC/CoreELEC/files/2078818/log-2018-06-07-03.09.13.zip)

**Comment by HeresJonny** [comment]
Please don't upload zipped log files, use a pastebin site and link here. Also, how did you install CE on a Rockchip device?

**Comment by azidman** [comment]
its a nexbox a95x s905x.

which logs should i put to pastebin?
kodi + system?
