### ISSUE TITLE
8.90.3 doesn't switch to 4K on S912

### ISSUE THREAD

**Issue by newkind** [CoreELEC/CoreELEC#111]
First of all thank you for the new update.

I just updated my KIII Pro and when I wanted to test it on 4K videos I noticed that my TV doesn't switch to 4K resolution like on 8.90.2 - it stays on 1080p. I switched to 4,4,4 10bit and HDR is working fine with BT2020 but the resolution seems to be the issue.

At first I tried to display track params by hitting "o" on keyboard and the track is being reported as 4K but the image itself doesn't looke like it. It less visible when playing mkv because of the high bitrate, but it's way more obvious on 4K live TV channels.

Does anyone else has this issue?

**Comment by boot2k3** [comment]
You need to set in Settings->System->Display->Whitelist all the desired resolutions/refresh rates you want to use
More details about this new kodi feature here:
https://github.com/xbmc/xbmc/pull/13274

**Comment by newkind** [comment]
That didn't worked. After whitelisting all resolutions (as my Sony Bravia should handle all of them) - the TV still reports 1080 plus I end up now with black screen and "no signal" message.

**Comment by Raybuntu** [comment]
It's working here for me. Maybe your TV can't handle the colorspace in those resolutions?

**Comment by newkind** [comment]
It's a Sony Bravia KD-55XE9005 from 2017 - pretty new TV that was working with everything I was able to throw at it. On 8.90.2 everything was fine with colorspace and resolutions.

After switching from 4,4,4 - 10bit to 4,4,4 - 8bit it looks like the TV now switches to 4K - which is weird as my TV 100% supports 10bits. Not sure also how this will affect HDR.

The other thing I noticed is that when I play live tv channels in 4K - it refreshes the picture after 2 seconds of playing, which also didn't happened before. This is happening only on 4K channels.

In my personal opinion somethings not quite right here.

**Comment by boot2k3** [comment]
Also try to check this setting if it enabled:
https://www.sony.co.uk/electronics/support/articles/00167580

**Comment by Raybuntu** [comment]
Are you by any chance using 4K videos with 50 or 60fps? Because 444,10bit with these framerates is out of the spec.

**Comment by newkind** [comment]
Ok, looks like it's solved. As it turns out my TV doesn't support 444,10bit on HDMI port 1 even though the enchanced channel is active and full data passthrough. I switched the HDMI from port 1 to port 3 and now everything seems to be fine. Sorry guys for bugging you! :)
