### ISSUE TITLE
8.90.3 - Adjust display refresh rate doesn't work on Amlogic S912 (KVIM2)

### ISSUE THREAD

**Issue by nemoforum** [CoreELEC/CoreELEC#113]
Just updated to 8.90.3 and found that automatic display refresh rate adjustment doesn't work: display refresh rate keeps at 60 fps even video is 25 fps or 23.976.

I've tried hard reset - the same issue.

8.90.2 - worked OK.

**Comment by boot2k3** [comment]
See my 1st comment here
https://github.com/CoreELEC/CoreELEC/issues/111
You need select whitelist resolutions

**Comment by nemoforum** [comment]
Ah, I see. Not so obvious.
I did search before posting this issue, but I fail =)
My apologies and thank you for so quick reply!

**Comment by nemoforum** [comment]
Petition/suggestion: add information like this into change log.
Thanks!
