### ISSUE TITLE
Music Player Crashes CE v 8.90.3

### ISSUE THREAD

**Issue by redger-au** [CoreELEC/CoreELEC#114]
Playing music in v8.90.3 on S905x Mecool Pro+ with 2/16 ... crashes consistently & repeatedly
Playing with party mode or from genre / all  with random and repeat all
V 8.90.3 was installed via auto update (from 8.90.2) and update appeared to complete normally

[log-2018-06-09-00.32.14.zip](https://github.com/CoreELEC/CoreELEC/files/2086498/log-2018-06-09-00.32.14.zip)

Subjectively it appears to occur soon after moving to a new track. The new track starts to play and then kodi restarts (within 5-10 secs ?)

NOTE that this is not the Mecool hardware with RAM issues. This hw has been checked and is not showing RAM or temperature issues

UPDATE #1: Changed 
(a) CEC adapter to not send any signals when screensaver starts 
(b) Audio settings to "keep alive always"
Now playing for 20 mins / multiple tracks and has not crashed (yet) whereas crashed within 10 mins previously.

Update #2: No changes, ran for 3 hours then crashed (kodi restarted).
would more logging help ?

**Comment by HeresJonny** [comment]
Disable Shadertoy.
