### ISSUE TITLE
8.90.3 Netflix App Crashes and not working

### ISSUE THREAD

**Issue by skcih** [CoreELEC/CoreELEC#115]
Was working fine before. Unit auto updated itself and now netflix app is not work. I tried to downgrade to the last release of the OS and it does not work as it seems a few addons are permanently changed (inputstream adaptive as I can't downgrade it even with a zip from the repo). Netflix app works in the downgrade of the release but when playing a video it says that inputstreamadaptive is not compatable any more since its the updated version.

I updated back to the new release and here is the log I receive. Netfilix will not open and just errors out. Log is at the link.

https://pastebin.com/NTapwKLd

**Comment by Raybuntu** [comment]
You need to update the NF addon. It was reported working on Kodinerds.
