### ISSUE TITLE
ShaderToy v1.1.8.2 from CoreELEC repo not working

### ISSUE THREAD

**Issue by P01da** [CoreELEC/CoreELEC#116]
ShaderToy will not work on my S905 or S905X boxes with any build since 8.2.4. After I upgraded to 8.90.3, I noticed that I **_was_** able to select a visualisation from the on-screen menu of the player, and it displayed for the whole playlist and exited correctly - until I rebooted the box. From then on, any track selected with ST enabled, **_does_** play, but kodi GUI stops and the Player GUI never shows, so after that track ends (without any change to the display, which is still on the source list) the box needs to be rebooted since Kodi (not CE) has stopped. If I uninstall ST and reboot, then reinstall ST it will work again until the box is reset after which it fails as described above. After several cycles of doing this, installing ST results in the Visualisation Pre-sets not being available from the Player GUI any more, even prior to resetting, and so selection is unavailable
I appreciate this could be a kodi issue but could it not also be an error introduced in the v1.1.8.2 add-on code when it was updated (presumably to make it compatible with the kodi 18 builds) ?
If you need any logs, just give me a clue where to get them for you because this is a good add-on that I would really like to have working again but can't seem to find out who can fix it.
Thanks

**Comment by adamg88** [comment]
I don't think this addon has been updated for Leia, the problem is a lot of the code has changed since Krypton, so themes and addons alike all need to be updated to continue working.

https://github.com/notspiff/visualization.shadertoy

**Comment by P01da** [comment]
Since the Author is now apparently aware, I guess there's no more to do but wait. Thanks for the reply ;)
