### ISSUE TITLE
Playing extras blanks display at end

### ISSUE THREAD

**Issue by prisoner881** [CoreELEC/CoreELEC#117]
Auto updated to 8.90.3 yesterday.  Platform is ODroid C2 using Plex for Kodi.  Playing any of the extra features on any title results in a blank display when it's done playing.  The interface is still "alive" because I can use the remote and hear the audio effects of moving around the UI.  Hitting the "exit" or "back" button will result in it asking "Do you want to exit Plex?" popping up.  If I exit Plex for Kodi and restart the add-on everything works normally again until I play another extra.

Note this does NOT occur when playing feature films.

This may be a Plex for Kodi issue and not a CoreELEC issue but since it doesn't actually crash anything it's hard to tell.

**Comment by HeresJonny** [comment]
No log no issue

**Comment by prisoner881** [comment]
If someone would tell me where the log file is I'll gladly include it.  Please bear with me.  I've never reported an issue before so I'm unfamiliar with the procedure.
