### ISSUE TITLE
FWD/REV seek broken

### ISSUE THREAD

**Issue by prisoner881** [CoreELEC/CoreELEC#118]
Platform ODroid C2 with Plex for Kodi.  Doing a FFWD or REV seek does not work.  It'll let you scrub about two clicks FWD or REV but then the UI goes away and becomes unresponsive to further seeks.  You can still stop the movie and resume it so nothing's crashed.

Possible this is just a Plex for Kodi bug and not a CoreELEC issue but since it won't crash I'm not sure.

**Comment by adamg88** [comment]
No log, no help
