### ISSUE TITLE
Internal DVB-C/S adapter issues (S912 KIII Pro)

### ISSUE THREAD

**Issue by chex84** [CoreELEC/CoreELEC#12]
when doing a fresh installation of  'CoreElec.8.90.0' the only internal adapter visible/working is this one:
"avalink avl6862 DVB-T"
The **internal** DVB-C/S won't show up in the tvheadened backend.

If you upgrade from an earlier (devel) build, the adapters are just working fine.

**Comment by afl1** [comment]
THV in repository is broken. Use [service.tvheadend42-9.0.114.zip](https://mega.nz/#!fkE1yTIY!DSUP72meD1ERocWnmZU0wFxgh2w9XEcCE_gof85wwtU).

**Comment by chex84** [comment]
you're right :-)
I installed service.tvheadend44-9.0.120 via ZIP Installation...that did it
everything seems to work now 👍
