### ISSUE TITLE
Ftps not working after update to 8.90.3

### ISSUE THREAD

**Issue by Doktor-X** [CoreELEC/CoreELEC#121]
Hi i have kimsufi server running windows 10 and filezilla ftp server, after update to 8.90.3 coreelec on my mecool pro l i was running 8.90.1 and all was ok after that i updated to .3 and cant connect to my server after that i downgraded back to .1 and all is ok so did something change if needed ill upload log but ill need to reupgrade once again

**Comment by boot2k3** [comment]
No logs, no help
In any case it's a kodi changes
You can try found your answer on kodi forum. May be this is your case:
https://forum.kodi.tv/showthread.php?tid=331918
