### ISSUE TITLE
DTB for mxq pro 4k?

### ISSUE THREAD

**Issue by tuxedo0801** [CoreELEC/CoreELEC#15]
Hey there,

you release already works great with wetek play 2.

But for my MXQ PRO 4K (see images attached) I'm still struggling with the right DTB ...

I currently have a running kodi from @kszaq. It's already a few months old now. There I had used a DTB name like

gxbb_p200_1G_mxq_pro_4k.dtb (I memoried this with a sticker on the bottom).

Now there is only kind of generic DTB for this.

I tried:

gxbb_p200_1G_100M.dtb
gxbb_p200_1G_1Gbit.dtb

Any hints which DTB is the right one?
I really want to switch to the new release to be able to use the new kodi which supports the stream interface so that I can use Prime Video like on my Wetek Play 2 Box, which is now running with CoreElec ;-)

br,
Alex

![img_20180418_174448](https://user-images.githubusercontent.com/2862906/38943163-04d5aa40-4331-11e8-8d5a-a930ed220c10.jpg)
![img_20180418_174501](https://user-images.githubusercontent.com/2862906/38943164-04f3e352-4331-11e8-9ca3-8b5050bffff0.jpg)

**Comment by arthur-liberman** [comment]
You didn't say what the problem is with booting that box.

**Comment by tuxedo0801** [comment]
Sorry... It stops booting at the white MXQ Pro logo ...

**Comment by tuxedo0801** [comment]
P212 1G now boots... seems that this is a S905x and not a S905 like p200 from last version?!

still having issues with ir-remote. But I think there was something in FAQ ... need to read.

**Comment by arthur-liberman** [comment]
The box does say 905X on the label. So it's likely a S905X.

**Comment by adamg88** [comment]
It's the same kernel that is in kszaq 8.2 so it should be the same dtb

https://m.banggood.com/MXQ-Pro-4K-Ultimate-KODI-Android-5_1-Lollipop-Amlogic-S905-Quad-Core-1GB8GB-TV-Box-Android-Mini-PC-p-1015008.html

Quick Google search reveals mxq pro 4k is a S905X box
