### ISSUE TITLE
Build for RK3328

### ISSUE THREAD

**Issue by alorbach** [CoreELEC/CoreELEC#16]
I am interested in building this image for my Rock64 devices (RK3328), but it stucks building here: 

[11/44] Building CXX object src/libcec/CMakeFiles/cec.dir/adapter/Linux/LinuxCECAdapterCommunication.cpp.o
FAILED: src/libcec/CMakeFiles/cec.dir/adapter/Linux/LinuxCECAdapterCommunication.cpp.o 
/home/al/git/CoreELEC/build.CoreELEC-RK3328.arm-9.0-devel/toolchain/bin/armv8a-libreelec-linux-gnueabi-g++  -Dcec_EXPORTS -I/home/al/git/CoreELEC/build.CoreELEC-RK3328.arm-9.0-devel/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/p8-platform -I../src/libcec -I../src/libcec/../../include -I/home/al/git/CoreELEC/build.CoreELEC-RK3328.arm-9.0-devel/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/python2.7 -march=armv8-a+crc -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mcpu=cortex-a53 -mfloat-abi=hard -mfpu=crypto-neon-fp-armv8 -fomit-frame-pointer -Wall -pipe -Os  -flto -ffat-lto-objects -std=c++11 -Wall -Wextra -Wno-missing-field-initializers -Os -DNDEBUG -fPIC -MD -MT src/libcec/CMakeFiles/cec.dir/adapter/Linux/LinuxCECAdapterCommunication.cpp.o -MF src/libcec/CMakeFiles/cec.dir/adapter/Linux/LinuxCECAdapterCommunication.cpp.o.d -o src/libcec/CMakeFiles/cec.dir/adapter/Linux/LinuxCECAdapterCommunication.cpp.o -c ../src/libcec/adapter/Linux/LinuxCECAdapterCommunication.cpp
In file included from ../src/libcec/adapter/Linux/LinuxCECAdapterCommunication.cpp:42:0:
../src/libcec/adapter/Linux/LinuxCECAdapterCommunication.h:66:27: error: 'CEC::cec_logical_addresses CEC::CLinuxCECAdapterCommunication::GetLogicalAddresses()' marked 'override', but does not override
     cec_logical_addresses GetLogicalAddresses(void) override;
                           ^~~~~~~~~~~~~~~~~~~
[12/44] Building CXX object src/libcec/CMakeFiles/cec.dir/adapter/AdapterFactory.cpp.o
FAILED: src/libcec/CMakeFiles/cec.dir/adapter/AdapterFactory.cpp.o 
/home/al/git/CoreELEC/build.CoreELEC-RK3328.arm-9.0-devel/toolchain/bin/armv8a-libreelec-linux-gnueabi-g++  -Dcec_EXPORTS -I/home/al/git/CoreELEC/build.CoreELEC-RK3328.arm-9.0-devel/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/p8-platform -I../src/libcec -I../src/libcec/../../include -I/home/al/git/CoreELEC/build.CoreELEC-RK3328.arm-9.0-devel/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/python2.7 -march=armv8-a+crc -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mcpu=cortex-a53 -mfloat-abi=hard -mfpu=crypto-neon-fp-armv8 -fomit-frame-pointer -Wall -pipe -Os  -flto -ffat-lto-objects -std=c++11 -Wall -Wextra -Wno-missing-field-initializers -Os -DNDEBUG -fPIC -MD -MT src/libcec/CMakeFiles/cec.dir/adapter/AdapterFactory.cpp.o -MF src/libcec/CMakeFiles/cec.dir/adapter/AdapterFactory.cpp.o.d -o src/libcec/CMakeFiles/cec.dir/adapter/AdapterFactory.cpp.o -c ../src/libcec/adapter/AdapterFactory.cpp
In file included from ../src/libcec/adapter/AdapterFactory.cpp:63:0:
../src/libcec/adapter/Linux/LinuxCECAdapterCommunication.h:66:27: error: 'CEC::cec_logical_addresses CEC::CLinuxCECAdapterCommunication::GetLogicalAddresses()' marked 'override', but does not override
     cec_logical_addresses GetLogicalAddresses(void) override;
                           ^~~~~~~~~~~~~~~~~~~
../src/libcec/adapter/AdapterFactory.cpp: In member function 'CEC::IAdapterCommunication* CEC::CAdapterFactory::GetInstance(const char*, uint16_t)':
../src/libcec/adapter/AdapterFactory.cpp:185:58: error: invalid new-expression of abstract class type 'CEC::CLinuxCECAdapterCommunication'
     return new CLinuxCECAdapterCommunication(m_lib->m_cec);
                                                          ^
In file included from ../src/libcec/adapter/AdapterFactory.cpp:63:0:
../src/libcec/adapter/Linux/LinuxCECAdapterCommunication.h:46:9: note:   because the following virtual functions are pure within 'CEC::CLinuxCECAdapterCommunication':
   class CLinuxCECAdapterCommunication : public IAdapterCommunication, public P8PLATFORM::CThread
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/libcec/CECProcessor.h:39:0,
                 from ../src/libcec/adapter/AdapterFactory.cpp:39:
../src/libcec/adapter/AdapterCommunication.h:149:35: note: 	virtual CEC::cec_logical_addresses CEC::IAdapterCommunication::GetLogicalAddresses() const
     virtual cec_logical_addresses GetLogicalAddresses(void) const = 0;
                                   ^~~~~~~~~~~~~~~~~~~
[16/44] Building CXX object src/libcec/CMakeFiles/cec.dir/LibCEC.cpp.o

------------

I am using Debian 9 to build, which worked fine for LibreElec builds (Also Raybuntu's versions).

**Comment by Raybuntu** [comment]
Currently we only support Amlogic projects. I haven't tried building RK for weeks now. I assume some RK specific patch is broken.

**Comment by alorbach** [comment]
Got it to build by adding the latest libcec changes from libreelec: 
https://github.com/alorbach/CoreELEC/commit/85b2e5c37fa24b25dd85a804d44f7dd2898762ff
https://github.com/alorbach/CoreELEC/commit/a0b9134c36cd9a4caf4288bd9b523d634d50be03

However the image is far from stable lol ...
