### ISSUE TITLE
no tv-adapter available on 9.0 dev build.

### ISSUE THREAD

**Issue by menotuu** [CoreELEC/CoreELEC#2]
no tv-adapter available, only IPTV.

Mecool KI Pro
S905D 16G/2G
installed on sdcardgxl_p230_k1_pro.dtb
CoreELEC-S905.arm-9.0-devel-1523108117.img.gz (2018-04-07 17:39 | 134MB)

fresh install.

**Comment by adamg88** [comment]
Have you enabled crazycat dvb driver?

**Comment by menotuu** [comment]
newest crazycat dvb driver solved the error. sorry for false alarm
