### ISSUE TITLE
Sometimes lircd.conf is working, sometimes not

### ISSUE THREAD

**Issue by VelocityPeter** [CoreELEC/CoreELEC#23]
Hi, 
after copying my lircd.conf to ".config" folder sometimes it works and after a reboot it does not work anymore. But then sporadically it is still working again after a few reboots or after the system freezed. Attached you find my lircd.conf settings. It's also the same behavior in the "LibreELEC-Odroid_C2.arm-9.0-devel-..." images. I hope you can fix this :). Thanks in advance!

![lircd_conf](https://user-images.githubusercontent.com/38566260/39062084-b139fda4-44c6-11e8-83c9-ec25345b34aa.GIF)

**Comment by afl1** [comment]
You are in wrong repository as the issue is not in CoreELEC but in you. Read first FAQ in this thread [https://forum.libreelec.tv/thread/12055-8-90-0-coreelec-for-s905-s912-devices/?pageNo=1]()
