### ISSUE TITLE
Missing dependency to kodi.binary.instance.pvr

### ISSUE THREAD

**Issue by tuxedo0801** [CoreELEC/CoreELEC#25]
Trying to install tvheadend pvr addon on CE 8.90.0, but only get this message in kodi.log

```
14:02:18.534 T:4002411392   ERROR: CAddonInstallJob[pvr.hts]: Die Abhängigkeit auf kodi.binary.instance.pvr in Version 5.9.0 konnte nicht aufgelöst werden.
```
How do I fix this? I do not find kodi.binary.instance.pvr v5.9.0

I expected that this dependency is resolved and downloaded automatically?

**Comment by Raybuntu** [comment]
By updating to 8.90.1
https://github.com/CoreELEC/CoreELEC/releases/tag/8.90.1

**Comment by tuxedo0801** [comment]
wtf? okay, cool, update. Let me check...
