### ISSUE TITLE
Live TV tvheadend zapping into blackscreen

### ISSUE THREAD

**Issue by pienoet** [CoreELEC/CoreELEC#26]
Hi,

There is an issue with the tvheadend client on my odroid C2.
I just updated from 8.90.0 to 8.90.1 and this issue still persist.

It's easy to reproduce just start a channel and zap to another channel and you get a black screen.
Then live tv freeze.
Ssh acces is still there so i have to reboot.

Here is a debug log. 
http://ix.io/18qZ](url)

Hope this is good enough..

Thanks!

**Comment by adamg88** [comment]
Stop playback before zapping to new channel.

**Comment by pienoet** [comment]
Thanks i do that all the time.
Is this issue a WIP?
Or can’t be fixed?

**Comment by pienoet** [comment]
@adamg @afl1 found out it was addon related.
After removing librespot addon zapping/switching to other channels is working fine.

**Comment by adamg88** [comment]
Glad you got it sorted
