### ISSUE TITLE
Need any help?

### ISSUE THREAD

**Issue by FFY00** [CoreELEC/CoreELEC#28]
Hey, do you need any help with the development?

**Comment by Raybuntu** [comment]
Help is always welcome.

**Comment by FFY00** [comment]
Where can I help then? I didn't find any list of issues or any TODO list.

**Comment by Raybuntu** [comment]
There is no TODO list and probably the first point in that list would be to make a TODO list lol.
You can actually work on whatever makes you the most fun. We use slack to communicate. I can send you an invite to your email address on GitHub?
