### ISSUE TITLE
Only one of 2 tuners is detected

### ISSUE THREAD

**Issue by Coolzero82** [CoreELEC/CoreELEC#29]
Hello, TvHeadend recognizes only one of the two tuners of my Hauppauge WinTV dual USB stick https://www.amazon.de/Hauppauge-Fernsehen-Tuner-dual-HD-Stick-Receiver/dp/B011Z7I0JY

Under LibreElec Krypton 19 of Raybuntu both tuners were displayed and could also be used.

The Hauppauge addon is active as well as the Crazycat addon

The problem exists under CoreElec 8.90.0 as well as under 8.90.1

Enclosed a Trace Log TVH, as well as the Kodi Log
![tvh](https://user-images.githubusercontent.com/38628642/39097688-f626d4ba-465f-11e8-9292-100f1c5cff0d.png)

lsusb liefert
```
`lsusb -vd 2040:0265

Bus 001 Device 003: ID 2040:0265 Hauppauge 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x2040 Hauppauge
  idProduct          0x0265 
  bcdDevice            1.00
  iManufacturer           3 HCW
  iProduct                1 dualHD
  iSerial                 2 0011569275
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           55
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0000  1x 0 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x85  EP 5 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0000  1x 0 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       1
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x03ac  1x 940 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x85  EP 5 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x03ac  1x 940 bytes
        bInterval               1
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  bNumConfigurations      1
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0000
  (Bus Powered)
`
```

[TVH.zip](https://github.com/CoreELEC/CoreELEC/files/1935883/TVH.zip)
[kodi.zip](https://github.com/CoreELEC/CoreELEC/files/1935909/kodi.zip)

**Comment by afl1** [comment]
Driver supporting both tuners  for  2040:0265 Hauppauge WinTV-dualHD DVB is included in Hauppauge drivers addon only. You have to select Add-ons -> LibreELEC Module Drivers ->Choose DVB driver module -> DVB drivers for Hauppauge.

**Comment by Coolzero82** [comment]
Hello,
Unfortunately, this does not work with the Hauppauge repo, if I activate only this under services, then I get garkeinen none of the two tuners displayed, only if I activate the Crazycat repo I get one of the two tuners
![dvb](https://user-images.githubusercontent.com/38628642/39145606-90c560fc-4734-11e8-9717-b55958aff2c9.jpg)

**Comment by afl1** [comment]
Try to install this crazycat dvb addon test version: [driver.dvb.crazycat-9.0.0.zip](https://mega.nz/#!yptU1YoQ!xSPusbSc2aNAqhpDss5RuZTj01Um87NUWyLOmwZzEos).

**Comment by Coolzero82** [comment]
With this package, both tuners are displayed and könnedriver.dvb.crazycat-9.0.0.zipn also be used. however, I now have very common TVH disconnects. The TVH trace is attached
[TVH.zip](https://github.com/CoreELEC/CoreELEC/files/1940922/TVH.zip)

**Comment by afl1** [comment]
Try also this version: [driver.dvb.crazycat-9.0.1.zip](https://mega.nz/#!ets0HTqS!fUelycewBSHkFGHBtErTmbNIt8ouK0N4KyyUgBHASdA).

**Comment by JohnBoyz** [comment]
I also have a similar problem trying to use 2 x DVB-T USB dongles.
The  driver.dvb.crazycat-9.0.1.zip  caused a non-boot issue with a fast scrolling screen of lines of output.
I see some 'oops' and 'die' lines there but have no way of capturing them that I know of.

I did a second attempt having wiped STORAGE and after first successful boot installed the driver from Zip and had the same result. I had not set up anything, or even plugged in the dongles at this time.

Using released install each dongle is operational on its lonesome.
When the second dongle is set up it causes the problem ....  showing intermittently and interfering with the correct working of the first dongle.

I tried 2 x RTL2832 and also 1 each RTL2832 and AF9013/5. 
When either type is used as a single tuner they work well.

If there are any suggestions I will attempt them.

**Comment by Coolzero82** [comment]
@ afl1 after John Boyz message, is it "safe" to install the 9.0.1?

**Comment by herrwusel** [comment]
@Coolzero82 I had problems with my Hauppauge Solo. After some trying I found out that the product id was different from the one mentioned on Linux tv[1]. So maybe you can try what worked for me[2].

[1] https://www.linuxtv.org/wiki/index.php/Hauppauge_WinTV-dualHD
[2] https://forum.libreelec.tv/thread/11573-problem-with-hauppauge-wintv-solohd-on-amlogic-s912-device-8-90-3-le-9-0-alpha/

**Comment by afl1** [comment]
There is the latest update for hauppauge drivers addon: [https://mega.nz/#!foEVkAwT!WYnCLxb1WkXIUXrch3Dd8pKynCEAmo6pmmkFNLj-icE](driver.dvb.hauppauge-9.0.0.zip)

**Comment by JohnBoyz** [comment]
>  @JohnBoyz Why are you not sure of the dtb source? All DTBs sit right on the root of a SD card in the device_tree folder.

Because I changed it, copying from another USB stick, and the device tree folder on the test stick was empty so I had nothing to compare it with.

**Comment by Coolzero82** [comment]
@ afl1 with the update from you driver.dvb.hauppauge-9.0.0.zip shows after a reboot no tuner, if the crazy cat is not activated, the log is in the appendix
[kodi.zip](https://github.com/CoreELEC/CoreELEC/files/1957294/kodi.zip)
[TVH.zip](https://github.com/CoreELEC/CoreELEC/files/1957295/TVH.zip)

**Comment by Coolzero82** [comment]
@ afl1 with the crazycat update driver.dvb.crazycat-9.0.1.zip. I have exactly the same problem as John Boyz, the box gets stuck at the start, attached a photo of it and the Kodi log
![crazycat9 1](https://user-images.githubusercontent.com/38628642/39392399-614da652-4ab5-11e8-8a3a-0b40cfb5d1ff.jpg)
[kodi.zip](https://github.com/CoreELEC/CoreELEC/files/1957310/kodi.zip)

**Comment by afl1** [comment]
Crazycat 9.0.1 is faulty, don't use it. I updated si2168 demodulator driver to the latest crazycat media_build changes. Try this version:[driver.dvb.crazycat-9.0.0-si2168.zip](https://mega.nz/#!Cw00URRa!_nuJWIzgTyiGgM56Lve9MyU7JsCI0Cn2S5gpAJCRUIs).

**Comment by Coolzero82** [comment]
Hello,
With the version I can not get a picture anymore and the TVH server needs a very long time about 4 to 5 minutes to connect to the TVH client. Both are on Wetek Play 2. Can this be related to the Crazycat or is that another problem?
Enclosed the logs
[kodi.zip](https://github.com/CoreELEC/CoreELEC/files/1959602/kodi.zip)
[TVH.zip](https://github.com/CoreELEC/CoreELEC/files/1959603/TVH.zip)

**Comment by Coolzero82** [comment]
I have tested the driver.dvb.crazycat-9.0.0-si2168.zip. again, and the problem is still the same, the TVH Server is need to two minutes ago to start after Kodi has started, and the connect the the TVH Client needs two minutes again
