### ISSUE TITLE
CPU gets stuck at 100%

### ISSUE THREAD

**Issue by ukmark62** [CoreELEC/CoreELEC#3]
Testing latest devel build CoreELEC-S905.arm-9.0-devel-1523108117 and notice that during playback one of the CPUs becomes stuck at 100%

Have tried several videos - all end up with one CPU getting stuck at 100% within a few seconds from starting playback. This has not happened before with previous Leia builds that I'm aware of.

My box is Sunvell T95M - S905x with 2Gb RAM. Installed on microSD card.
DTB is gxl_p212_2g.dtb

**Comment by adamg88** [comment]
I am not able to reproduce this issue installing the same build on my own hardware, this could be related to an addon you have installed or some other issue but it is impossible to say without logs being provided

**Comment by ukmark62** [comment]
This could be a one-time upgrade issue. Since I rebooted, the issue has not re-occurred. I also have a S905 box and the same thing happened there. Once I rebooted after the initial upgrade, everything has been fine.
I seem to recall a user in the LE forum reported high CPU usage after the initial upgrade - once he rebooted, the issue has gone away. I'm closing this one.
