### ISSUE TITLE
Kodi unable to start when NAND is cleared

### ISSUE THREAD

**Issue by rafacouto** [CoreELEC/CoreELEC#32]
Starting from SD with a dumped CoreELEC-KVIM2.arm-8.90.1.img.gz and NAND cleared, CE starts the kernel and services, but kodi is not able to init and restarts the system (it doesn't occur if I stop kodi.service, watchdog?). 

This is the log from the serial console: https://pastebin.com/egptSTn1

And this is the systemctl status kodi.service:

    Jan 01 00:00:22 CoreELEC kodi.sh[2934]: library "libgui.so" wasn't loaded and RTLD_NOLOAD prevented it
    Jan 01 00:00:22 CoreELEC kodi.sh[2934]: failed to get gralloc module: (No such file or directory)
    Jan 01 00:00:22 CoreELEC kodi.sh[2934]: kodi.bin: /data/CoreELEC/build.CoreELEC-KVIM2.arm-9.0-devel/libhybris-070c3ab/egl/platforms/fbdev/eglplatform_fbdev.cpp:29: void fbdevws_init_module(ws_egl_interface*): Assertion `0' failed.
    Jan 01 00:00:22 CoreELEC kodi.sh[2934]: Aborted (core dumped)
    Jan 01 00:00:22 CoreELEC systemd[1]: Stopping Kodi Media Center...

**Comment by afl1** [comment]
Sorry, I don't understand what do you mean under "Starting from SD with a dumped CoreELEC-KVIM2.arm-8.90.1.img.gz and NAND cleared". This image is for burning to new SD card and running CE from this SD card without using internal flash memory. You cannot dump component from .img and put them to already running LE version. It doesn't work, but you can upgrade LE to CE 8.90.1 by putting .img or .tar to upgrade folder (/storage/.upgrade or samba share Upgrade).

**Comment by rafacouto** [comment]
I have restored stock android to the nand memory and the same SD card with CE is running perfect including kodi. I conclude U-boot by android is doing some initialization in hardware that CE is missing when starting in vim2 without any u-boot in the internal flash memory.

**Comment by P01da** [comment]
I conclude you've no idea what you're doing
