### ISSUE TITLE
Kodi freezes when trying to install Gaia

### ISSUE THREAD

**Issue by newkind** [CoreELEC/CoreELEC#34]
I just noticed a weird thing - when you try to install Gaia addon, and you click on Gaia name in it's repository - it freezes whole Kodi. You have to do the `systemctl restart kodi` in order to get it back working. Other addons from this repository installed just fine.

**Comment by adamg88** [comment]
It could be that the add-on is not yet compatible with Leia have you contacted the add-on developer?

**Comment by newkind** [comment]
Not yet, I just installed CoreElec and I'm playing with it. The odd thing is that this isn't happening in the addon. It's when I try to install it. When you click on it's name - you should get a window with description, Install button etc. This is the moment when Kodi freezes.

**Comment by HeresJonny** [comment]
That looks like the kind of add-on that no support should be offered for.

**Comment by Raybuntu** [comment]
No support for piracy addons!

**Comment by adamg88** [comment]
Didn't realize it was a piracy addon
