### ISSUE TITLE
kernel modules for HiFi Shield / Shield plus / Shield 2

### ISSUE THREAD

**Issue by sagittarius06** [CoreELEC/CoreELEC#36]
First, I would like to thank the authors of CoreELEC because of the very good job they've done but also everyone involved in free software.

I can understand if technically it might be very difficult to compile sources modules for the patched CoreELEC kernel.

But if possible, it would be absolutely great to have the Shield sound card family working on the C2 because the sound is really really good.

For example, the HiFi Shield 2 needs these kernel modules (which are available on Ubuntu, diet-pi and Volumio):

"aml_i2c"
"snd-soc-pcm512x"
"snd-soc-pcm512x-i2c"
 "snd-soc-odroid-dac2"

And there is also an excellent script to make the hardkernel original sound cards work out of the box by installing the kernel modules, the right systemd file here: https://forum.odroid.com/viewtopic.php?f=118&t=24415

Thanks for reading me.

**Comment by adamg88** [comment]
I would be happy to accept a PR on this and add it to CE.

**Comment by Raybuntu** [comment]
I have a Hifi Shield 2 and last time I checked it was working without those alsa modules. You have simultaneous output from Shield and HDMI.

**Comment by sagittarius06** [comment]
Thank you very much for your answer Raybuntu.
I've tried and yes it works.

According to the page here: http://www.hardkernel.com/main/products/prdt_info.php?g_code=G147589529288 does it mean that:
"This HiFi Shield 2 is partially functional on Android. The output format is fixed at 44.1Khz/16bit stereo. There is no Analog volume control capability either due to limited AOSP audio HAL implementation" ?

I'm going to test high resolution musical files (88.4 /96 / 192 kHz).

Have a nice day
