### ISSUE TITLE
Music Playback Causes Crash

### ISSUE THREAD

**Issue by redger-au** [CoreELEC/CoreELEC#37]
When playing music the whole machine crashes.
Coreelec 8.90.1 running on either M8S+ (S905)  Or MeCool M8S Pro+ (S905x) both with 2GB RAM and running from SDCard (both 16GB). Behaviour began on v8.90.0. MeCool Pro+ exhibited this behaviour with both versions ... and both were "clean" installs (different SDCards). The M8S+ was updated from previous LibreElec version to 8.90.1

Data stored on NFS share. Kodi using MySQL database for content library
Machines connected via USB WiFi dongle .... and in 1 test connected via native RJ45 ie. wired ethernet, to a different device with different hdmi cable.

Music is selected by Genre. Play all artists, all albums, all songs. Set repeat = all, random = on.
Should be ~35 hours worth of playing (ignoring randomisation).
Machine eventually fails within 24 hours and either locks up or "stops" ie. kodi unresponsive even if ssh session still "alive" or kodi auto-restarts

Logs from MeCool M8S Pro+ are attached (2 different test runs, first wifi, second wired). Temperature data has been included in each, no temperature issues observed (can be an issue with MeCool)

[log-2018-04-24-03.42.56_wtemp.zip](https://github.com/CoreELEC/CoreELEC/files/1945953/log-2018-04-24-03.42.56_wtemp.zip)
[log-2018-04-25-00.06.04_wtemp.zip](https://github.com/CoreELEC/CoreELEC/files/1945954/log-2018-04-25-00.06.04_wtemp.zip)

PS These boxes have been running LibreElec & CoreElec for a while now and this behaviour is new

**Comment by adamg88** [comment]
This is a problem due to recent updates with ffmpeg, flac support was broken, the next build will contain ffmpeg 4.0 which should fix the issue.
