### ISSUE TITLE
Resume Playback not visible on CoreELEC

### ISSUE THREAD

**Issue by KyleSanderson** [CoreELEC/CoreELEC#38]
I updated my build from kszaq's last LibreELEC release on an s905 box. My libraries were in-place upgraded and now only show completions but no partial progress on a particular video library item.

**Comment by boot2k3** [comment]
This is Kodi settings
Check Settings->Media->Library->Hide progress of library updates for required type of media

**Comment by KyleSanderson** [comment]
@boot2k3 nope that's the top right notification saying which shows are currently being added to the library. Nothing to do with this regression/bug.

**Comment by Raybuntu** [comment]
I can still resume playback.

**Comment by boot2k3** [comment]
Just tested on 8.90.1, it shows a progress in video library and in "In progress movie"
Try to start file, pause not in the beginning of file and check again

**Comment by KyleSanderson** [comment]
@TheChief79 it's possible, I'm running Confluence by JazzX

**Comment by vinylity** [comment]
I think it might have something to do with this version of Kodi.

**Comment by adamg88** [comment]
This would be a Kodi related issue which is out of the scope of our purview, the main focus with CoreELEC is fixing issues relating directly to the hardware that our builds run, this issue would be better taken up on the Kodi forums.

Not all skins have been updated to be fully supported yet on Leia as it is still in Alpha.
