### ISSUE TITLE
inputstream.adaptive has an important fix in version >= 2.2.13

### ISSUE THREAD

**Issue by mapfde** [CoreELEC/CoreELEC#4]
Currently there are audio stream selection issues when using Sandmann79's amazon vod plugin. An update to inputstream.adaptive is needed to a version >= 2.2.13. See here for the relevant discussion:

https://www.kodinerds.net/index.php/Thread/44211-Release-Amazon-Prime-Instant-Video/?postID=457415#post457415

**Comment by adamg88** [comment]
inputstream.adaptive will be updated with the next build

**Comment by Raybuntu** [comment]
@piotrasd  Not public yet. Will be published probably today. But I think the inputstream update will be in our official alpha2.

**Comment by adamg88** [comment]
[inputstream.adaptive-2.2.15.0.zip](https://github.com/CoreELEC/CoreELEC/files/1913915/inputstream.adaptive-2.2.15.0.zip)
Latest version of the addon attached, this should suffice for now.
