### ISSUE TITLE
Remote on S905X very slow to respond

### ISSUE THREAD

**Issue by Petelombardo** [CoreELEC/CoreELEC#40]
The remote on the older Libreelec build used to be snappy on my Ticid S905X unit.   On CoreElec, it's painfully slow and there may or may not be double-events at times.  Navigating is quite painful.

Excerpt from dmesg...
[   14.005435@3] Registered IR keymap rc-empty
[   14.005875@3] input: meson-ir as /devices/c8100580.meson-ir/rc/rc0/input2
[   14.006139@3] rc0: meson-ir as /devices/c8100580.meson-ir/rc/rc0
[   14.052757@1] lirc_dev: IR Remote Control driver registered, major 229 
[   14.055062@1] rc rc0: lirc_dev: driver ir-lirc-codec (meson-ir) registered at minor = 0

**Comment by adamg88** [comment]
First CE != LE, there has never been official LE releases so please don't compare, I don't know if you are referring to kszaq/wrxtasy or my own builds, they all operate differently.

Secondly which version are you running

Thirdly have you read the following thread RE: adjusting IR timings and delays? https://forum.libreelec.tv/thread/11643-le9-0-remote-configs-ir-keytable-amlogic-devices/

And lastly have you considered using CEC or an RF remote other than the garbage that comes prepackaged with your device?

**Comment by Petelombardo** [comment]
Thanks for the tips.

The eventlircd binary is not even found on my CE clean installation.   I
was unable to follow the steps listed at the URL that was provided.

Thanks,
-Pete

**Comment by Petelombardo** [comment]
Forgot to provide the version...
CoreELEC (official): 8.90.1 (S905.arm)

**Comment by adamg88** [comment]
You can ignore the eventlircd step as it was removed in .1 so is not necessary.

**Comment by TJC** [comment]
+1 to this issue -- on a S905X Beelink MiniMX II, the remote went from being quite snappy on your old builds, to diificult to use -- either slow, or with occasional double-ups.

My "fix" has been to use a different remote, so I'm good for now -- but I'm sure many people do use the remotes that come with their boxes, and it's clearly not the actual remote's fault, since it used to work fine.

It sounds like it's possible to fix with some timing adjustments -- so maybe they could be baked into a future release?

**Comment by arthur-liberman** [comment]
The remote system on AML was broken in the recent build in Kodi, so a workaround was implemented, which is not perfect.
We all recommend using RF remote controls. They always work, and they work much better than the cheapo IR stuff that comes with the boxes.

**Comment by Petelombardo** [comment]
I think there might be a kernel patch for the sluggish amlogic remotes...
https://patchwork.kernel.org/patch/10277541/

**Comment by wodgey** [comment]
So how can I use this kernel patch? Can I simply mount the squashfs and plonk it into the image? Or would I need to compile from sources?
(Mounting squash - I'm comfortable doing. Compiling from source - a bit beyond me)

**Comment by adamg88** [comment]
We have addressed this issue in 8.90.2 which will be released shortly. If anybody still has issues following that feel free to re-open this issue.
