### ISSUE TITLE
could not mount /dev/mmcblk0p1 wetek hub

### ISSUE THREAD

**Issue by Condorello** [CoreELEC/CoreELEC#44]
Hi, i got this error on a fresh install on my wetek hub. The micro-sd is new, 16gb Sandisk Ultra.
Any advice?

**Comment by adamg88** [comment]
You need to elaborate more

**Comment by Condorello** [comment]
I've weOS on nand. I download the tar.bz and flashed with librelec tool on the SD card. Start the box with the recovery button and i saw the CoreElec logo, after that 4/5 lines (installing and similar). At reboot (dual boot wetek) if i press power for start from external (sd) i got that :(

**Comment by adamg88** [comment]
Did you copy and rename the wetek hub dtb?

**Comment by Condorello** [comment]
Shit... sorry.... i understood that dtb was auto-recognized during first boot and moved automagically :(

**Comment by adamg88** [comment]
No these are not Wetek specific images like LE, they are generic S905 images that require manual intervention on your part, you only need to do it once then that is it.
