### ISSUE TITLE
Rock64/RK3328 audio passthrough issues.

### ISSUE THREAD

**Issue by immortalShadow** [CoreELEC/CoreELEC#45]
Playing back videos with passthrough results in a weird static, buzzing sound.  Disabling passthrough fixes the issue, and plays just fine.

Videos that use DTS for the audio track do not create this buzzing.

 The videos that create the buzzing use DTS-MA, DTS-HD, DTS-X, Dolby Atmos, and Dolby Digital. (This isn't an "official" list, and only tested with what I had on hand. I'm sure there is more audio formats this occurs on)

Please be aware this isn't my setup, as using Kodi on my old HTPC works just fine with passthrough. If this is needed, my reciever is Denon AVR 5208.

**Comment by adamg88** [comment]
We do not currently support RK builds.

**Comment by Raybuntu** [comment]
And it's also a known issue/limitation. It doesn't work with RK Kernel/Kodi
