### ISSUE TITLE
Remote config. Not eventlircd?

### ISSUE THREAD

**Issue by wodgey** [CoreELEC/CoreELEC#46]
Just updated to 8.90.1 and there's a few buttons on my remote that don't work.

Tried following the instructions that I previously used, to create the rc keymap. 
Eventlircd can't be stopped though as it's not running.

How do I get the context menu button working again? It's not critical, as since being handled as a keyboard, long-press "ok" works. Still, it's twanging my OCD's

**Comment by HeresJonny** [comment]
https://github.com/xbmc/xbmc/pull/13823
might be fixed in Kodi

**Comment by adamg88** [comment]
Did you read the release notes at all? It does say that IR has changed to keyboard mode, you can skip the steps with eventlircd as we removed it as it is no longer needed.

If you look Wiki it gives you a whole list of what the key code is for each function https://kodi.wiki/view/Keyboard_controls

KEY_C is what you use for content menu

This issues system is not a Q&A for general support questions and is for reporting bugs and/or hardware issues.

**Comment by wodgey** [comment]
Whoops ..... Soz!

I'd actually just read the release notes and was coming back here to edit/close the issue myself.

Where is a suitable place for q&a, that doesn't cause offense or irritation?

**Comment by adamg88** [comment]
Forums
