### ISSUE TITLE
Stuck at kodi loading screen S912

### ISSUE THREAD

**Issue by kassak** [CoreELEC/CoreELEC#48]
Hi! Just tried to run latest build (8.90.1) on my TX92 (3/32) box.
It've stuck on "Kodi Leia" loading screen: no ssh, no reaction to remote, power button.
My device tree is gxm_q200_3g.dtb
LibreElec 8.2.2.3 runs smooth.
I'm not sure my [kodi.log](https://github.com/CoreELEC/CoreELEC/files/1959034/kodi.log) have anything interesting.

How can I make it work?
How can I view system log (dmesg) in that case?

offtop: Why build for 64bit S912 is 32bit?

**Comment by adamg88** [comment]
If your stuck at the loading screen then it is probably a DTB related issue 

SSH is enabled by default so I can only thing that your box is hanging, see above

We build the kernel as 64bit with a 32bit userspace.

**Comment by kassak** [comment]
I finally managed to start it. I've masked kodi.service on SD card. After boot there was no ssh, but nmap 've said that SAMBA is up. I've found logs there:
```
Apr 30 07:21:56 CoreELEC systemd[1]: Starting OpenSSH server daemon...
Apr 30 07:21:56 CoreELEC systemd[1]: Started OpenSSH server daemon.
Apr 30 07:21:56 CoreELEC sshd[3002]: key_load_private: invalid format
Apr 30 07:21:56 CoreELEC sshd[3002]: key_load_public: invalid format
Apr 30 07:21:56 CoreELEC sshd[3002]: Could not load host key: /storage/.cache/ssh/ssh_host_rsa_key
Apr 30 07:21:56 CoreELEC sshd[3002]: key_load_private: invalid format
Apr 30 07:21:56 CoreELEC sshd[3002]: key_load_public: invalid format
Apr 30 07:21:56 CoreELEC sshd[3002]: Could not load host key: /storage/.cache/ssh/ssh_host_dsa_key
Apr 30 07:21:56 CoreELEC sshd[3002]: key_load_private: invalid format
Apr 30 07:21:56 CoreELEC sshd[3002]: key_load_public: invalid format
Apr 30 07:21:56 CoreELEC sshd[3002]: Could not load host key: /storage/.cache/ssh/ssh_host_ecdsa_key
Apr 30 07:21:56 CoreELEC sshd[3002]: key_load_private: invalid format
Apr 30 07:21:56 CoreELEC sshd[3002]: key_load_public: invalid format
Apr 30 07:21:56 CoreELEC sshd[3002]: Could not load host key: /storage/.cache/ssh/ssh_host_ed25519_key
Apr 30 07:21:56 CoreELEC sshd[3002]: sshd: no hostkeys available -- exiting.
Apr 30 07:21:56 CoreELEC systemd[1]: sshd.service: Main process exited, code=exited, status=1/FAILURE
Apr 30 07:21:56 CoreELEC systemd[1]: sshd.service: Failed with result 'exit-code'.
Apr 30 07:21:58 CoreELEC systemd[1]: sshd.service: Service hold-off time over, scheduling restart.
Apr 30 07:21:58 CoreELEC systemd[1]: sshd.service: Scheduled restart job, restart counter is at 19.
Apr 30 07:21:58 CoreELEC systemd[1]: Stopped OpenSSH server daemon.
```
I've removed .cache/ssh, got ssh working, unmasked kodi. And it works.
Strange that kodi hung on broken ssh, strange that ssh was broken on freshly burned SD.
Sorry for bothering you.

**Comment by adamg88** [comment]
Upgrading from Krypton is not always compatible, we have tried to make it seamless as possible but unfortunately the odd bug still appears

**Comment by kassak** [comment]
FYI:
> on freshly burned SD

Nope that wasn't update, that was `dd`'ed image.
