### ISSUE TITLE
struggling to mount cifs share

### ISSUE THREAD

**Issue by wodgey** [CoreELEC/CoreELEC#5]
I can mount perfectly via the file-manager.

I cannot mount via ssh using either mount -t cifs OR using the .mount file in system.d.

unsure what log files you'll need. i'm posting from a tablet but should be able to grab a transcript from juicessh

**Comment by adamg88** [comment]
Can you please tell me which command you are using to try and mount via SSH?

**Comment by wodgey** [comment]
Tried various commands.

Even "mount -t cifs //192.168.0.245/share /storage/nas" returns fail with invalid argument.

**Comment by chatbuddy21** [comment]
just to share I have a working cifs mount via libreelec, currently running the latest devel build

mount -t cifs -o vers=1.0,username=admin,password=xxxx,rw //192.168.1.1/sda2 /storage/smb

**Comment by wodgey** [comment]
Chatbuddy.

Thanks, this works.

However, when using 'systemctl start storage-nas.mount' it tries the mount string in a different order, which fails

CoreELEC:~ # mount //192.168.0.245/share/ /storage/nas -t cifs -o username=share,password=share,rw,vers=1.0
mount: mounting //192.168.0.245/share/ on /storage/nas failed: Invalid argument
CoreELEC:~ #

**Comment by chatbuddy21** [comment]
I just use the autostart.sh to mount my shares

**Comment by chatbuddy21** [comment]
CoreELEC:~/.config # cat autostart.sh #!/bin/sh
(sleep 30;
mount -t cifs -o vers=1.0,username=admin,password=xxxx,rw //192.168.1.1/sda2 /storage/smb;
 )&

**Comment by wodgey** [comment]
@chatbuddy21 

have aleady done this, after your suffestion of the devel build worked :)

Now, just need to get my head around why transmission-daemon won't work and i'm a happy camper

**Comment by adamg88** [comment]
Never seen systemd used to mount shares nevertheless glad the issue is resolved for you.

**Comment by wodgey** [comment]
I've also been tinkering with an Intel atom, libreelec x86_64 build. 

For some reason using the autostart.sh method doesn't work. Mounting via system.d works.

**Comment by adamg88** [comment]
You would have to take this up on the LE forums under the x86 device section and report the issue as we don't build for that platform. I think milhouse will most certainly wan't to fix that if it is indeed an issue as x86 is his domain.

**Comment by wodgey** [comment]
Cool. I was just sharing here as I found it interesting.
I'm working away in London for a few days so I can't do anything right now
