### ISSUE TITLE
Problem playing some HEVC Videos

### ISSUE THREAD

**Issue by Sholander** [CoreELEC/CoreELEC#50]
Recently found some HEVC videos that don't play on my X92 box with Hardware Decoding enabled. With disabled hardware decoding they all play OK.

[Debug Log](https://pastebin.com/dbFbJ5aL)

40 seconds [sample file](https://drive.google.com/open?id=1jESip16RT8zkSTgOp8BQj0wk9s_HB6-N)

All these files (including the above sample) play OK in Android 7.1.2 on Kodi Leia Alpha2, on SPMC 16.7.4 and on MrMC Lite 3.6.0 with Hardware decoding...

The box is X92_S912_q201 3/32G - 1GB Ethernet on Android 7.1.2
running CoreELEC-S905.arm-8.90.1

**Comment by Sholander** [comment]
The box is X92_S912_q201 3/32G - 1GB Ethernet on Android 7.1.2 
running CoreELEC-S905.arm-8.90.1

**Comment by afl1** [comment]
You video is faulty or wrongly encoded. Amlogic hw decoder is unable to recover from this errors:
From kernel log:

>[  283.439105@0] [0]H265 dec err local reset.
[  283.439289@2] [0]nal type 0, discard 1
[  283.439852@2] [0]init_decode_head_hw: (1280, 720) body_size 0x167600 header_size 0xf00
[  283.439879@2] [0]hevc_recover HEVC_SHIFT_BYTE_COUNT=1189
[  286.449144@0] [0]H265 dec err local reset.
[  286.449340@2] [0]nal type 0, discard 1
[  286.449907@2] [0]init_decode_head_hw: (1280, 720) body_size 0x167600 header_size 0xf00
[  286.449933@2] [0]hevc_recover HEVC_SHIFT_BYTE_COUNT=1649
[  289.449134@0] [0]H265 dec err local reset.
[  289.449284@2] [0]nal type 0, discard 1
[  289.449847@2] [0]init_decode_head_hw: (1280, 720) body_size 0x167600 header_size 0xf00
[  289.449873@2] [0]hevc_recover HEVC_SHIFT_BYTE_COUNT=1b09
[  291.365911@3] codec:video_blackout_policy_store(0)
[  291.366088@3] [tsync_avevent]event:1, param 1
[  291.366111@3] video pause!

**Comment by Sholander** [comment]
Tnx, should have suspected that, because to get these files to play on SPMC-16.7.4 I had to turn off AmCodec, leaving only MediaCodec and MediaCodec (Surface) on...

**Comment by Sholander** [comment]
Just to folowup, since I have many of such files:
On latest CE.8.90.3 they ALL play OK with Hardware Decoding enabled, so probably are not faulty or wrongly decoded...
