### ISSUE TITLE
libcec not working with JBL soundbar + samsung tv

### ISSUE THREAD

**Issue by Condorello** [CoreELEC/CoreELEC#51]
Hi, maybe is not related to coreelec, but yesterday i bough a new cheap soundbar for my bedroom:
-jbl bar studio (harman/kardon) to use with my tv samsung D8000 and my s905 kodi boxes.
The TV is connected trough ARC-HDMI to the soundbar, which is capable of that.
All is working fine, but when i power off TV at the wakeup the d-pad keys on the remote doesn't respond.
ChannelUP/DOWN, STOP, PLAY/PAUSE are working, but arrow UP-DOWN-LEFT-RIGHT-OK not.
If i do a reboot of the kodi box, using ssh or also the smartphone app KORE (kodi isn't stuck) all start working again.
Here a log for libcec. Moreovere if i launch cec-client without any argument, at the wakeup the dpad doens't working at all, but if i launch it with "-r" option it answer at one-two presses (on a total of 10-15 presses...).

`LEcamera:~ # cec-client -r
using settings from EEPROM
No device type given. Using 'recording device'
CEC Parser created - libCEC version 4.0.2
no serial port given. trying autodetect: 
 path:     /dev/aocec
 com port: AOCEC

opening a connection to the CEC adapter...
DEBUG:   [             209]	Broadcast (F): osd name set to 'Broadcast'
NOTICE:  [             209]	connection opened
DEBUG:   [             209]	processor thread started
DEBUG:   [             209]	<< Broadcast (F) -> TV (0): POLL
TRAFFIC: [             209]	<< f0
DEBUG:   [             271]	>> POLL sent
DEBUG:   [             271]	TV (0): device status changed into 'present'
DEBUG:   [             271]	<< requesting vendor ID of 'TV' (0)
TRAFFIC: [             271]	<< f0:8c
DEBUG:   [            1361]	expected response not received (87: device vendor id)
TRAFFIC: [            1361]	<< f0:8c
TRAFFIC: [            1554]	>> 0f:87:9c:64:5e
DEBUG:   [            1554]	TV (0): vendor = Harman/Kardon (9c645e)
DEBUG:   [            1554]	>> TV (0) -> Broadcast (F): device vendor id (87)
DEBUG:   [            1554]	expected response received (87: device vendor id)
NOTICE:  [            1554]	registering new CEC client - v4.0.2
DEBUG:   [            1554]	detecting logical address for type 'recording device'
DEBUG:   [            1554]	trying logical address 'Recorder 1'
DEBUG:   [            1554]	<< Recorder 1 (1) -> Recorder 1 (1): POLL
TRAFFIC: [            1554]	<< 11
WARNING: [            1741]	Write: write failed
TRAFFIC: [            1741]	<< 11
WARNING: [            2061]	Write: write failed
DEBUG:   [            2061]	>> POLL not sent
DEBUG:   [            2061]	using logical address 'Recorder 1'
DEBUG:   [            2061]	Recorder 1 (1): device status changed into 'handled by libCEC'
DEBUG:   [            2061]	Recorder 1 (1): power status changed from 'unknown' to 'on'
DEBUG:   [            2061]	Recorder 1 (1): vendor = Pulse Eight (001582)
DEBUG:   [            2061]	Recorder 1 (1): CEC version 1.4
DEBUG:   [            2061]	AllocateLogicalAddresses - device '0', type 'recording device', LA '1'
DEBUG:   [            2063]	Recorder 1 (1): osd name set to ''
DEBUG:   [            2063]	Recorder 1 (1): menu language set to 'eng'
DEBUG:   [            2063]	AutodetectPhysicalAddress - autodetected physical address '1000'
DEBUG:   [            2063]	Recorder 1 (1): physical address changed from ffff to 1000
DEBUG:   [            2063]	<< Recorder 1 (1) -> broadcast (F): physical address 1000
TRAFFIC: [            2063]	<< 1f:84:10:00:01
NOTICE:  [            4211]	CEC client registered: libCEC version = 4.0.2, client version = 4.0.2, firmware version = 5, logical address(es) = Recorder 1 (1) , physical address: 1.0.0.0,  compiled on Sat Apr 21 23:30:36 UTC 2018 by ray@asimov on Linux 4.4.0-112-generic (x86_64), features: P8_USB, DRM, P8_detect, AOCEC
DEBUG:   [            4211]	<< Recorder 1 (1) -> TV (0): OSD name ''
TRAFFIC: [            4211]	<< 10:47
DEBUG:   [            4301]	<< requesting power status of 'TV' (0)
TRAFFIC: [            4302]	<< 10:8f
TRAFFIC: [            4537]	>> 01:90:00
DEBUG:   [            4537]	TV (0): power status changed from 'unknown' to 'on'
DEBUG:   [            4537]	>> TV (0) -> Recorder 1 (1): report power status (90)
waiting for input
DEBUG:   [            4538]	expected response received (90: report power status)

TRAFFIC: [          244329]	>> 01:44:01
DEBUG:   [          244329]	SetCurrentButton up (1) D:0ms cur:1
DEBUG:   [          244329]	key pressed: up (1) current(ff) duration(0)
DEBUG:   [          244329]	Changed key up (1) D:0ms cur:ff
DEBUG:   [          244329]	key pressed: up (1, 0)
DEBUG:   [          244329]	making Recorder 1 (1) the active source
NOTICE:  [          244329]	>> source activated: Recorder 1 (1)
DEBUG:   [          244329]	CheckKeypressTimeout T:482.358
DEBUG:   [          244329]	Key up: idle (duration:0) (1) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          244329]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
DEBUG:   [          244830]	CheckKeypressTimeout T:482.859
DEBUG:   [          244831]	Key unknown: idle (duration:501) (ff) timeout:3399060ms (rel:1000,rep:0,prs:0,rel:0)
TRAFFIC: [          245398]	>> 01:45
DEBUG:   [          245398]	>> TV (0) -> Recorder 1 (1): user control release (45)
TRAFFIC: [          246003]	>> 01:44:00
DEBUG:   [          246003]	SetCurrentButton select (0) D:0ms cur:0
DEBUG:   [          246003]	key pressed: select (0) current(ff) duration(0)
DEBUG:   [          246003]	Changed key select (0) D:0ms cur:ff
DEBUG:   [          246003]	key pressed: select (0, 0)
DEBUG:   [          246003]	CheckKeypressTimeout T:484.032
DEBUG:   [          246003]	Key select: idle (duration:0) (0) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          246003]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
DEBUG:   [          246504]	CheckKeypressTimeout T:484.533
DEBUG:   [          246504]	Key unknown: idle (duration:501) (ff) timeout:3399060ms (rel:1000,rep:0,prs:0,rel:0)
TRAFFIC: [          248647]	>> 01:44:02
DEBUG:   [          248647]	SetCurrentButton down (2) D:0ms cur:2
DEBUG:   [          248647]	key pressed: down (2) current(ff) duration(0)
DEBUG:   [          248647]	Changed key down (2) D:0ms cur:ff
DEBUG:   [          248647]	key pressed: down (2, 0)
DEBUG:   [          248647]	CheckKeypressTimeout T:486.676
DEBUG:   [          248648]	Key down: idle (duration:0) (2) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          248648]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
DEBUG:   [          249149]	CheckKeypressTimeout T:487.178
DEBUG:   [          249149]	Key unknown: idle (duration:502) (ff) timeout:3399060ms (rel:1000,rep:0,prs:0,rel:0)
TRAFFIC: [          249436]	>> 01:44:02
DEBUG:   [          249436]	SetCurrentButton down (2) D:0ms cur:2
DEBUG:   [          249436]	key pressed: down (2) current(ff) duration(0)
DEBUG:   [          249436]	Changed key down (2) D:0ms cur:ff
DEBUG:   [          249436]	key pressed: down (2, 0)
DEBUG:   [          249436]	CheckKeypressTimeout T:487.465
DEBUG:   [          249436]	Key down: idle (duration:0) (2) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          249436]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
DEBUG:   [          249936]	CheckKeypressTimeout T:487.965
DEBUG:   [          249937]	Key unknown: idle (duration:500) (ff) timeout:3399060ms (rel:1000,rep:0,prs:0,rel:0)
TRAFFIC: [          251600]	>> 01:44:02
DEBUG:   [          251600]	SetCurrentButton down (2) D:0ms cur:2
DEBUG:   [          251600]	key pressed: down (2) current(ff) duration(0)
DEBUG:   [          251600]	Changed key down (2) D:0ms cur:ff
DEBUG:   [          251600]	key pressed: down (2, 0)
DEBUG:   [          251600]	CheckKeypressTimeout T:489.629
DEBUG:   [          251600]	Key down: idle (duration:0) (2) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          251601]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
TRAFFIC: [          251815]	>> 01:44:02
DEBUG:   [          251815]	SetCurrentButton down (2) D:0ms cur:2
DEBUG:   [          251815]	key pressed: down (2) current(2) duration(0)
DEBUG:   [          251815]	key pressed: down (2, 0)
DEBUG:   [          251815]	CheckKeypressTimeout T:489.844
DEBUG:   [          251815]	Key down: idle (duration:0) (2) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          251815]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
TRAFFIC: [          252181]	>> 01:44:02
DEBUG:   [          252182]	SetCurrentButton down (2) D:0ms cur:2
DEBUG:   [          252182]	key pressed: down (2) current(2) duration(0)
DEBUG:   [          252182]	key pressed: down (2, 0)
DEBUG:   [          252182]	CheckKeypressTimeout T:490.211
DEBUG:   [          252182]	Key down: idle (duration:0) (2) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          252182]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
DEBUG:   [          252683]	CheckKeypressTimeout T:490.712
DEBUG:   [          252684]	Key unknown: idle (duration:1083) (ff) timeout:3399060ms (rel:1000,rep:0,prs:0,rel:0)
TRAFFIC: [          252827]	>> 01:44:02
DEBUG:   [          252827]	SetCurrentButton down (2) D:0ms cur:2
DEBUG:   [          252827]	key pressed: down (2) current(ff) duration(0)
DEBUG:   [          252827]	Changed key down (2) D:0ms cur:ff
DEBUG:   [          252827]	key pressed: down (2, 0)
DEBUG:   [          252827]	CheckKeypressTimeout T:490.856
DEBUG:   [          252828]	Key down: idle (duration:0) (2) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          252828]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
DEBUG:   [          253328]	CheckKeypressTimeout T:491.357
DEBUG:   [          253328]	Key unknown: idle (duration:501) (ff) timeout:3399060ms (rel:1000,rep:0,prs:0,rel:0)
TRAFFIC: [          253359]	>> 01:44:02
DEBUG:   [          253359]	SetCurrentButton down (2) D:0ms cur:2
DEBUG:   [          253359]	key pressed: down (2) current(ff) duration(0)
DEBUG:   [          253359]	Changed key down (2) D:0ms cur:ff
DEBUG:   [          253359]	key pressed: down (2, 0)
DEBUG:   [          253359]	CheckKeypressTimeout T:491.388
DEBUG:   [          253359]	Key down: idle (duration:0) (2) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          253360]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
TRAFFIC: [          253601]	>> 01:45
DEBUG:   [          253601]	key released: down (2) D:242ms
DEBUG:   [          253601]	>> TV (0) -> Recorder 1 (1): user control release (45)
DEBUG:   [          252827]	SetCurrentButton down (2) D:0ms cur:2
DEBUG:   [          252827]	key pressed: down (2) current(ff) duration(0)
DEBUG:   [          252827]	Changed key down (2) D:0ms cur:ff
DEBUG:   [          252827]	key pressed: down (2, 0)
DEBUG:   [          252827]	CheckKeypressTimeout T:490.856
DEBUG:   [          252828]	Key down: idle (duration:0) (2) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          252828]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
DEBUG:   [          253328]	CheckKeypressTimeout T:491.357
DEBUG:   [          253328]	Key unknown: idle (duration:501) (ff) timeout:3399060ms (rel:1000,rep:0,prs:0,rel:0)
TRAFFIC: [          253359]	>> 01:44:02
DEBUG:   [          253359]	SetCurrentButton down (2) D:0ms cur:2
DEBUG:   [          253359]	key pressed: down (2) current(ff) duration(0)
DEBUG:   [          253359]	Changed key down (2) D:0ms cur:ff
DEBUG:   [          253359]	key pressed: down (2, 0)
DEBUG:   [          253359]	CheckKeypressTimeout T:491.388
DEBUG:   [          253359]	Key down: idle (duration:0) (2) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          253360]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
TRAFFIC: [          253601]	>> 01:45
DEBUG:   [          253601]	key released: down (2) D:242ms
DEBUG:   [          253601]	>> TV (0) -> Recorder 1 (1): user control release (45)waiting for input
waiting for input
waiting for input
waiting for input
waiting for input
waiting for input
waiting for input
waiting for input
waiting for input
waiting for input
waiting for input
waiting for input
waiting for input
waiting for input
waiting for input
waiting for input
waiting for input
waiting for input
waiting for input
TRAFFIC: [          291192]	>> 5f:72:00
DEBUG:   [          291192]	>> Audio (5): system audio mode status changed from on to off
DEBUG:   [          291192]	device Audio (5) status changed to present after command set system audio mode
DEBUG:   [          291193]	>> Audio (5) -> Broadcast (F): set system audio mode (72)
TRAFFIC: [          291860]	>> ff
TRAFFIC: [          292100]	>> 5f:84:20:00:05
DEBUG:   [          292100]	Audio (5): physical address changed from ffff to 2000
DEBUG:   [          292100]	>> Audio (5) -> Broadcast (F): report physical address (84)
TRAFFIC: [          326692]	>> ff
TRAFFIC: [          326933]	>> 5f:84:20:00:05
DEBUG:   [          326933]	>> Audio (5) -> Broadcast (F): report physical address (84)
TRAFFIC: [          336759]	>> 0f:32:69:74:61
DEBUG:   [          336759]	TV (0): menu language set to 'ita'
DEBUG:   [          336760]	>> TV (0) -> Broadcast (F): set menu language (32)
TRAFFIC: [          338316]	>> 5f:87:9c:64:5e
DEBUG:   [          338316]	Audio (5): vendor = Harman/Kardon (9c645e)
DEBUG:   [          338316]	>> Audio (5) -> Broadcast (F): device vendor id (87)
TRAFFIC: [          339209]	>> 5f:72:01
DEBUG:   [          339209]	>> Audio (5): system audio mode status changed from off to on
DEBUG:   [          339210]	>> Audio (5) -> Broadcast (F): set system audio mode (72)
TRAFFIC: [          340311]	>> 01:8c
DEBUG:   [          340311]	<< Recorder 1 (1) -> TV (0): vendor id Pulse Eight (1582)
TRAFFIC: [          340311]	<< 1f:87:00:15:82
DEBUG:   [          340312]	>> TV (0) -> Recorder 1 (1): give device vendor id (8C)
TRAFFIC: [          340615]	>> 01:83
DEBUG:   [          340616]	<< Recorder 1 (1) -> broadcast (F): physical address 1000
TRAFFIC: [          340616]	<< 1f:84:10:00:01
DEBUG:   [          340617]	>> TV (0) -> Recorder 1 (1): give physical address (83)
TRAFFIC: [          340832]	>> 01:46
DEBUG:   [          340832]	>> TV (0) -> Recorder 1 (1): give osd name (46)
DEBUG:   [          340832]	<< Recorder 1 (1) -> TV (0): OSD name ''
TRAFFIC: [          340833]	<< 10:47
TRAFFIC: [          342885]	>> 01:8d:02
DEBUG:   [          342885]	>> TV (0) -> Recorder 1 (1): menu request (8D)
DEBUG:   [          342885]	<< Recorder 1 (1) -> TV (0): menu state 'activated'
TRAFFIC: [          342886]	<< 10:8e:00
TRAFFIC: [          343181]	>> 01:1a:01
DEBUG:   [          343181]	>> TV (0) -> Recorder 1 (1): give deck status (1A)
DEBUG:   [          343182]	<< Recorder 1 (1) -> TV (0): deck status 'stop'
TRAFFIC: [          343183]	<< 10:1b:1a
TRAFFIC: [          343905]	>> 5f:84:20:00:05
DEBUG:   [          343906]	>> Audio (5) -> Broadcast (F): report physical address (84)
TRAFFIC: [          344646]	>> 5f:72:01
DEBUG:   [          344646]	>> Audio (5) -> Broadcast (F): set system audio mode (72)
TRAFFIC: [          346199]	>> 0f:85
DEBUG:   [          346199]	>> TV (0) -> Broadcast (F): request active source (85)
DEBUG:   [          346199]	>> 0 requests active source
NOTICE:  [          346199]	<< Recorder 1 (1) -> broadcast (F): active source (1000)
TRAFFIC: [          346199]	<< 1f:82:10:00
TRAFFIC: [          346408]	>> 01:8d:02
DEBUG:   [          346408]	>> TV (0) -> Recorder 1 (1): menu request (8D)
DEBUG:   [          346408]	<< Recorder 1 (1) -> TV (0): menu state 'activated'
TRAFFIC: [          346409]	<< 10:8e:00
TRAFFIC: [          346705]	>> 01:8d:02
DEBUG:   [          346705]	>> TV (0) -> Recorder 1 (1): menu request (8D)
DEBUG:   [          346706]	<< Recorder 1 (1) -> TV (0): menu state 'activated'
TRAFFIC: [          346706]	<< 10:8e:00
TRAFFIC: [          373848]	>> 01:45
DEBUG:   [          373848]	>> TV (0) -> Recorder 1 (1): user control release (45)
TRAFFIC: [          374558]	>> 01:44:02
DEBUG:   [          374558]	SetCurrentButton down (2) D:0ms cur:2
DEBUG:   [          374558]	key pressed: down (2) current(ff) duration(0)
DEBUG:   [          374558]	Changed key down (2) D:0ms cur:ff
DEBUG:   [          374558]	key pressed: down (2, 0)
DEBUG:   [          374558]	CheckKeypressTimeout T:612.587
DEBUG:   [          374558]	Key down: idle (duration:0) (2) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          374559]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
DEBUG:   [          375059]	CheckKeypressTimeout T:613.088
DEBUG:   [          375059]	Key unknown: idle (duration:501) (ff) timeout:3399060ms (rel:1000,rep:0,prs:0,rel:0)
TRAFFIC: [          375610]	>> 01:44:02
DEBUG:   [          375610]	SetCurrentButton down (2) D:0ms cur:2
DEBUG:   [          375610]	key pressed: down (2) current(ff) duration(0)
DEBUG:   [          375610]	Changed key down (2) D:0ms cur:ff
DEBUG:   [          375610]	key pressed: down (2, 0)
DEBUG:   [          375610]	CheckKeypressTimeout T:613.639
DEBUG:   [          375610]	Key down: idle (duration:0) (2) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          375611]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
TRAFFIC: [          375948]	>> 01:45
DEBUG:   [          375948]	key released: down (2) D:338ms
DEBUG:   [          375948]	>> TV (0) -> Recorder 1 (1): user control release (45)
TRAFFIC: [          377485]	>> 01:44:01
DEBUG:   [          377485]	SetCurrentButton up (1) D:0ms cur:1
DEBUG:   [          377485]	key pressed: up (1) current(ff) duration(0)
DEBUG:   [          377485]	Changed key up (1) D:0ms cur:ff
DEBUG:   [          377485]	key pressed: up (1, 0)
DEBUG:   [          377485]	CheckKeypressTimeout T:615.514
DEBUG:   [          377485]	Key up: idle (duration:0) (1) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          377486]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
TRAFFIC: [          377824]	>> 01:45
DEBUG:   [          377824]	key released: up (1) D:339ms
DEBUG:   [          377824]	>> TV (0) -> Recorder 1 (1): user control release (45)
TRAFFIC: [          403260]	>> 01:44:02
DEBUG:   [          403260]	SetCurrentButton down (2) D:0ms cur:2
DEBUG:   [          403260]	key pressed: down (2) current(ff) duration(0)
DEBUG:   [          403261]	Changed key down (2) D:0ms cur:ff
DEBUG:   [          403261]	key pressed: down (2, 0)
DEBUG:   [          403261]	CheckKeypressTimeout T:641.290
DEBUG:   [          403261]	Key down: idle (duration:0) (2) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          403261]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
DEBUG:   [          403761]	CheckKeypressTimeout T:641.790
DEBUG:   [          403762]	Key unknown: idle (duration:500) (ff) timeout:3399060ms (rel:1000,rep:0,prs:0,rel:0)
TRAFFIC: [          405601]	>> 01:44:02
DEBUG:   [          405602]	SetCurrentButton down (2) D:0ms cur:2
DEBUG:   [          405602]	key pressed: down (2) current(ff) duration(0)
DEBUG:   [          405602]	Changed key down (2) D:0ms cur:ff
DEBUG:   [          405602]	key pressed: down (2, 0)
DEBUG:   [          405602]	CheckKeypressTimeout T:643.631
DEBUG:   [          405602]	Key down: idle (duration:0) (2) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          405602]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
DEBUG:   [          406102]	CheckKeypressTimeout T:644.131
DEBUG:   [          406102]	Key unknown: idle (duration:500) (ff) timeout:3399060ms (rel:1000,rep:0,prs:0,rel:0)
TRAFFIC: [          413496]	>> 01:44:02
DEBUG:   [          413496]	SetCurrentButton down (2) D:0ms cur:2
DEBUG:   [          413496]	key pressed: down (2) current(ff) duration(0)
DEBUG:   [          413496]	Changed key down (2) D:0ms cur:ff
DEBUG:   [          413496]	key pressed: down (2, 0)
DEBUG:   [          413496]	CheckKeypressTimeout T:651.525
DEBUG:   [          413496]	Key down: idle (duration:0) (2) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          413497]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
TRAFFIC: [          413834]	>> 01:45
DEBUG:   [          413834]	key released: down (2) D:338ms
DEBUG:   [          413834]	>> TV (0) -> Recorder 1 (1): user control release (45)
TRAFFIC: [          415433]	>> 01:44:02
DEBUG:   [          415433]	SetCurrentButton down (2) D:0ms cur:2
DEBUG:   [          415433]	key pressed: down (2) current(ff) duration(0)
DEBUG:   [          415433]	Changed key down (2) D:0ms cur:ff
DEBUG:   [          415433]	key pressed: down (2, 0)
DEBUG:   [          415433]	CheckKeypressTimeout T:653.462
DEBUG:   [          415433]	Key down: idle (duration:0) (2) timeout:-171975360ms (rel:500,rep:0,prs:500,rel:0)
DEBUG:   [          415433]	>> TV (0) -> Recorder 1 (1): user control pressed (44)
DEBUG:   [          415934]	CheckKeypressTimeout T:653.963
DEBUG:   [          415934]	Key unknown: idle (duration:501) (ff) timeout:3399060ms (rel:1000,rep:0,prs:0,rel:0)
`

p.s. all works fine if i attach my Yamaha soundbar..

**Comment by Raybuntu** [comment]
The CEC line is jammed. That happens if you have devices with a flawed CEC implementation. AML cec driver has some issues if other devices are blocking the CEC path and it goes into TX BUSY state and resets after a while until it's dead. Kernel debug log would probably show this error. Nothing we can do really.
