### ISSUE TITLE
CEC not working on s912 

### ISSUE THREAD

**Issue by deleder2k** [CoreELEC/CoreELEC#55]
CEC stopped working after I've upgraded to 8.90.1 with my S912. I use a Sony TV. CEC on all my other devices work fine. I've tried to take the DTB from the img.gz and put in the root folder on the USB without any luck. Also tried to disable/enable CEC in Kodi settings without any luck.

**Comment by deleder2k** [comment]
`CoreELEC:~ # cec-client
No device type given. Using 'recording device'
CEC Parser created - libCEC version 4.0.2
no serial port given. trying autodetect: 
 path:     /dev/aocec
 com port: AOCEC

opening a connection to the CEC adapter...
DEBUG:   [             198]	Broadcast (F): osd name set to 'Broadcast'
NOTICE:  [             198]	connection opened
DEBUG:   [             199]	processor thread started
DEBUG:   [             199]	<< Broadcast (F) -> TV (0): POLL
TRAFFIC: [             199]	<< f0
DEBUG:   [            2233]	>> POLL sent
DEBUG:   [            2233]	TV (0): device status changed into 'present'
DEBUG:   [            2233]	<< requesting vendor ID of 'TV' (0)
TRAFFIC: [            2233]	<< f0:8c
DEBUG:   [            5393]	expected response not received (87: device vendor id)
TRAFFIC: [            5393]	<< f0:8c
DEBUG:   [            6483]	expected response not received (87: device vendor id)
NOTICE:  [            6483]	registering new CEC client - v4.0.2
DEBUG:   [            6483]	detecting logical address for type 'recording device'
DEBUG:   [            6483]	trying logical address 'Recorder 1'
DEBUG:   [            6483]	<< Recorder 1 (1) -> Recorder 1 (1): POLL
TRAFFIC: [            6483]	<< 11
WARNING: [            6683]	Write: write failed
TRAFFIC: [            6683]	<< 11
WARNING: [            6883]	Write: write failed
DEBUG:   [            6883]	>> POLL not sent
DEBUG:   [            6883]	using logical address 'Recorder 1'
DEBUG:   [            6883]	Recorder 1 (1): device status changed into 'handled by libCEC'
DEBUG:   [            6883]	Recorder 1 (1): power status changed from 'unknown' to 'on'
DEBUG:   [            6883]	Recorder 1 (1): vendor = Pulse Eight (001582)
DEBUG:   [            6883]	Recorder 1 (1): CEC version 1.4
DEBUG:   [            6883]	AllocateLogicalAddresses - device '0', type 'recording device', LA '1'
DEBUG:   [            6884]	Recorder 1 (1): osd name set to 'CECTester'
DEBUG:   [            6884]	Recorder 1 (1): menu language set to 'eng'
DEBUG:   [            6884]	AutodetectPhysicalAddress - autodetected physical address '3000'
DEBUG:   [            6884]	Recorder 1 (1): physical address changed from ffff to 3000
DEBUG:   [            6884]	<< Recorder 1 (1) -> broadcast (F): physical address 3000
TRAFFIC: [            6884]	<< 1f:84:30:00:01
WARNING: [            7063]	Write: write failed
TRAFFIC: [            7063]	<< 1f:84:30:00:01
NOTICE:  [            9103]	CEC client registered: libCEC version = 4.0.2, client version = 4.0.2, firmware version = 5, logical address(es) = Recorder 1 (1) , physical address: 3.0.0.0,  compiled on Sat Apr 21 23:36:12 UTC 2018 by ray@asimov on Linux 4.4.0-112-generic (x86_64), features: P8_USB, DRM, P8_detect, AOCEC
DEBUG:   [            9103]	<< Recorder 1 (1) -> TV (0): OSD name 'CECTester'
TRAFFIC: [            9103]	<< 10:47:43:45:43:54:65:73:74:65:72
DEBUG:   [            9413]	<< requesting power status of 'TV' (0)
TRAFFIC: [            9413]	<< 10:8f
DEBUG:   [           10503]	expected response not received (90: report power status)
TRAFFIC: [           10503]	<< 10:8f
waiting for input
DEBUG:   [           11593]	expected response not received (90: report power status)
TRAFFIC: [           13232]	>> 01
DEBUG:   [           13232]	<< POLL: TV (0) -> Recorder 1 (1)`

**Comment by Raybuntu** [comment]
Is CEC working on Android or have you tried going back a version? I heard of several cases where it was a hardware failure after some time.

**Comment by deleder2k** [comment]
It works now. Don't know what happened. Tried updating again, didn't work. Turned on/off device + CEC on both device and TV many times. Changed to HDMI 2 and changed cable. Worked! Thanks for the help. I'll blame Sony :)
