### ISSUE TITLE
"Freezing" / Extreme Slow down of device after turning TV on

### ISSUE THREAD

**Issue by diabl0w** [CoreELEC/CoreELEC#57]
After returning to my TV after a couple hours and turning it on, it seems that CoreELEC freezes. Technically however it seems like sometimes button pushes (via CEC) will go through about 5 minutes later so it's not completely frozen.

Also, generally it's a system wide freeze (i.e I can't ssh into the device either) however if persistent I can get in through ssh. Since the device wasn't active for a few hours there isn't much in the logs except for [code] ERROR: CAESinkALSA - snd_pcm_writei(-32) Broken pipe - trying to recover [/code] and the error repeats 91 times

It seems that this log error was in some of @Raybuntu older builds (http://www.wetekforums.com/v/discussion/29237/libreelec-krypton-leia-agile-play2-64bit-kernel-32bit-libs/p52) with the same freezing issue

Running 8.90.1 on Mecool M8s Pro

**Comment by adamg88** [comment]
We really need logs to diagnose issues like this, what addons do you have installed as I can leave my devices on for days without issue

**Comment by diabl0w** [comment]
log:

'20:02:40.629 T:3517105024  NOTICE: [plugin.video.elementum] [36mDEBU  main         ▶ Notification     [0mGot notification from xbmc/GUI.OnScreensaverDeactivated: {"shuttingdown":false}
20:02:59.978 T:4083364736   ERROR: CAESinkALSA - snd_pcm_writei(-32) Broken pipe - trying to recover
20:11:11.361 T:3517105024   ERROR: Previous line repeats 91 times.
20:11:11.389 T:3517105024  NOTICE: [plugin.video.elementum] [36mDEBU  main         ▶ Notification     [0mGot notification from xbmc/GUI.OnScreensaverActivated: null
20:11:16.822 T:3517105024  NOTICE: [plugin.video.elementum] [36mDEBU  main         ▶ Notification     [0mGot notification from xbmc/GUI.OnScreensaverDeactivated: {"shuttingdown":false}
20:11:57.591 T:4096003200   ERROR: GetDirectory - Error getting plugin://plugin.video.elementum/movies/
20:11:58.269 T:4096003200   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.elementum/movies/) failed
20:12:09.093 T:4083364736   ERROR: CAESinkALSA - snd_pcm_writei(-32) Broken pipe - trying to recover
20:27:48.704 T:2052240256   ERROR: Previous line repeats 74 times.'

I have elementum and hdhomerun pvr client installed and estuary mod skin

**Comment by diabl0w** [comment]
also I just read something interesting...  the way I turn on my TV is via an ExLink cable connected to a serial interface, and I read somewhere that this may interfere with hdmi-cec... is CAESinkALSA related to CEC? If so this might be the issue and I'll have to report back if the issue disappears when turning on the TV normally (not via serial)

**Comment by adamg88** [comment]
No CAESinkALSA is related to the sound subsystem.

I suspect something is causing a spike in your CPU as this would explain your slow system and SSH behaviour, my guess is it's probably your pirate torrent addon, unfortunately due to this I will be unable to help you further as we can not be seen as encouraging these activities.

**Comment by adamg88** [comment]
Unfortunately videos on YouTube speak to the opposite and we have air on the side of caution with questionable addons and can not be seen to be supporting or assistant in matters relating to them.

Please try and boot your system in a vanilla state with no addons and leave it for a day and see if you have the same issue, if you do then feel free to open another issue.

Best of luck.

**Comment by diabl0w** [comment]
I understand you're stance and me saying thanks wasn't sarcastic, you're
probably right about the cpu spike. I just checked and the device was quite
warm, probably addon related. I'll reopen if vanilla still has issue
