### ISSUE TITLE
CoreELEC-S905.arm-8.90.1 very slow with Playlist loader

### ISSUE THREAD

**Issue by Ken77Shiro** [CoreELEC/CoreELEC#59]
Hello guys,
I did a test with CoreELEC-S905.arm-8.90.0 and it is able to load my list with Playlist loader in less than 20 seconds, with 8.90.1 it takes more than 5 minutes.

Don't know if the problem is related to the addon or to the build of CoreELEC.

How can I help you to identify the problem? Do you need some log?

Many thanks!

**Comment by adamg88** [comment]
Need logs to help

**Comment by Ken77Shiro** [comment]
[kodi_playlist_loader_1.1.7.log.zip](https://github.com/CoreELEC/CoreELEC/files/1968678/kodi_playlist_loader_1.1.7.log.zip)

**Comment by Ken77Shiro** [comment]
[kodi_playlist_loader_1.2.0.log.zip](https://github.com/CoreELEC/CoreELEC/files/1968784/kodi_playlist_loader_1.2.0.log.zip)
