### ISSUE TITLE
DVB Channel switching - Image freezing

### ISSUE THREAD

**Issue by atreyuhere** [CoreELEC/CoreELEC#6]
As reported there are still issues when channel switching in LiveTV.

Used:
-MiniM8S (s905)
-Latest dev + device tree found in image (CoreELEC-S905.arm-9.0-devel-1523108117,  dtb gxbb_p200_2G_100M.dtb)
-TVMoziac (DVBLink) PVR Addon (latest from CE Repo)

Reproduce:
-Enable Debug Logging (componenets: A/V/Timing)
-Start Channel (HD) OK
-Next Channel (HD) OK
-Next Channel (HD) Image Freezes for about 8 seconds before catching up
-Next Channel (SD) Image Freezes
-Next Channel (SD) OK
-Next Channel (SD) Freezes
etc.

Debug log attached

Regards,

Atreyu
[01_KODI.zip](https://github.com/CoreELEC/CoreELEC/files/1898863/01_KODI.zip)

**Comment by adamg88** [comment]
This was designed this way by xbmc team, there was a recent commit into Kodi detailing this issue https://github.com/xbmc/xbmc/pull/13756

**Comment by atreyuhere** [comment]
Thankd for pointing this out.
Although i get the general idea, it’s kind of disappointing because the change results in much, much less fluid experience. Channel freezes for at least 8 seconds is not a ‘fix’ for a fluid experience in previous versions.

In any case, thanks for answering. I now know this will not improve sobi will have to stick eit 8.90.5, which handles channel switching like a champ.

I will trt and find out if ots possible to build 8.90.5 including an updated Kodi version to get rid of the incidental crash-on-stop bug

Thanks again!
