### ISSUE TITLE
Network@100 Mbit/s

### ISSUE THREAD

**Issue by Martner44** [CoreELEC/CoreELEC#62]
Hi there,
I am not sure if this is an actual issue... However, I've noticed this behaviour with LibreELEC before. My box (see details below) will always connect @ 100 MBit/s (wired ethernet) while it's capable of Gigabit connections.

With all the streaming, fanart/logo/you_name_it downloading going on, I wonder if it's possible to switch to Gigabit. If so, how do I do that?

Thanks in advance for any hint/feedback!

BTW, this is by far the fastest build I ever had installed on this box. Keep up the excellent work!!! And a big, big thank you for putting your time & effort into this!

_(Nexbox A95X).
(S905X)
RAM/Flash size (2GB/8GB)
Resolution (1080p).
Refresh rate (60 Hz).
Installed to external (SD Card)
CoreELEC 8.90.0
Linux 3.14.29 aarch64_

**Comment by Raybuntu** [comment]
I think you only assume you have a 1Gbit/s Ethernet. S905X boxes don't have 1Gbit/s Ethernet. And your box definitely not.
Some premium boxes Wetek, Minix or Odroid have 1Gbit/s Ethernet.

**Comment by arthur-liberman** [comment]
This USB 3.0 gigabit adapter works perfectly for me on my S905X boxes:
https://www.ebay.com/itm/112541143662

**Comment by Martner44** [comment]
Ooops, you're right. I mixed that up with my cubox-i. Sorry for that. And thanks to you, arthur-liberman, for the USB adapter link!
