### ISSUE TITLE
CoreElec copilation error on Debian 9

### ISSUE THREAD

**Issue by andresayang** [CoreELEC/CoreELEC#64]
Hi,
When googling for my compil error, I fall on this https://pastebin.com/SDdLbGjX witch is exactly the error I have ! (well the compilation log is for libreelec but i fall on the same for coreelec)

Another point, is there any way to get full iso 3d mvc working (on S912) ? (or are you working on this ?)

Thanks

**Comment by adamg88** [comment]
Your posting 2 separate issues and you have quoted someone elses error logs rather than your own.

**Comment by andresayang** [comment]
"Your posting 2 separate issues and you have quoted someone elses error logs rather than your own.": Yes I post someone else post, but I have exactly the same error with libssl.c.. I can post mine if you prefer, but it will show exactly the same.
About the 2 issues, i do not want to pollute, but i can make a second one if you like.

**Comment by andresayang** [comment]
Hi,

As it seems that I was not well understood, i'm closing this one to open a proper issue.

Sorry
