### ISSUE TITLE
Updating from kszaq's LE 8.2 build, mount error

### ISSUE THREAD

**Issue by trohnjavolta** [CoreELEC/CoreELEC#65]
Hello, just a minor issue when updating from kszaq's LE 8.2 build:
Mount error saying a partition with the label COREELEC can't be mounted.
Renaming the LIBREELEC partition to COREELEC solved it.
I also renamed the storage partition from LIBREELEC_DISK to STORAGE... don't know if that's necessary.
Maybe this can be done in update routine, idk.

**Comment by TheChief79** [comment]
That is a known issue i think.

**Comment by gelotus** [comment]
You must reburn your sd/usb with img, if you want you can save the content of /storage and restore after first boot
