### ISSUE TITLE
Fix for keyboard/mouse being detected as joystick in Linux

### ISSUE THREAD

**Issue by sinancetinkaya** [CoreELEC/CoreELEC#68]
There are some keyboards, mouses are recognized as joysticks by linux kernel.
Could you guys add a udev rule to fix that?
There is a good udev rule already prepared https://github.com/denilsonsa/udev-joystick-blacklist/blob/master/51-these-are-not-joysticks.rules

**Comment by sinancetinkaya** [comment]
Yes my keyboard is in that list.

**Comment by adamg88** [comment]
I have added the list to CoreELEC, you will notice the changes in 8.90.3.
