### ISSUE TITLE
Cross compiling for S912 on Debian 9 fails

### ISSUE THREAD

**Issue by andresayang** [CoreELEC/CoreELEC#69]
Hi,

I' trying to compile for Amlogic S912 on Debian 9 system and have error with libssl.c.
I have pre-download all necessary libs with: PROJECT=Amlogic DEVICE=S912 ARCH=arm tools/download-tool, then i compile with PROJECT=Amlogic DEVICE=S912 ARCH=arm make image
My linux system is: 
uname -a: Linux 4.9.0-6-amd64 SMP  Debian 4.9.88-1 (2018-04-29) x86_64 GNU/Linux
debian_version: 9.4
here my log:  [log.zip](https://github.com/CoreELEC/CoreELEC/files/1977541/log.zip)

Thanks

**Comment by gelotus** [comment]
Try to update your host gcc to v7

**Comment by andresayang** [comment]
"Try to delete your build directories rm -rf build.* and try again.": Yep, same error ... I'll try to build within virtualbox later.

**Comment by adamg88** [comment]
There must be something wrong in your build environment then, maybe a conflicting package is causing the issue.

When we do releases they are made on an Ubuntu 16.04 host as per the official LE wiki [here](https://wiki.libreelec.tv/compile) and there is no issues.

**Comment by andresayang** [comment]
Try on Ubuntu, compile fine.
I do not know what is going on Debian 9, i do not think about conflicting setup, my Debian 9 is almost a « fresh » install.
So i’m closing this one.
