### ISSUE TITLE
What's the difference between LibreELEC and CoreELEC?

### ISSUE THREAD

**Issue by numbqq** [CoreELEC/CoreELEC#7]
It's not a issue...

Just a question, What's the difference between LibreELEC and CoreELEC?

**Comment by adamg88** [comment]
CoreELEC is a fork of LE focused on fixing issues that LE has with running on Amlogic SoC's.

The LE development team has refused to allow a lot of the community based fixes as one of the long term goals in LE is to reduce reliance on patches and upstream fixes, however this is not always possible and as such LE has had to be forked as the current policy was leading to a poor quality builds with many issues.

The aim of CoreELEC is to mitigate these issues and continue development for Amlogic based products which has effectively currently seized within LE as there is no longer any active contributors for the platform.

**Comment by numbqq** [comment]
Thanks for your explanation.

**Comment by Raybuntu** [comment]
I would like to add that we are not limited to Amlogic. I work on Rockchip as well and we are open for new developers. We just happen to have a lot Amlogic Developers at the moment.

@numbqq If you like I can send you an invite for our Slack to your email address here on GH? You can join us there and ask questions and we might ask as well.

**Comment by numbqq** [comment]
Hi @Raybuntu 

It's great! So what should I do?

**Comment by Raybuntu** [comment]
@numbqq I've send an invite to our Slack to the email address you have here on GitHub.

**Comment by numbqq** [comment]
I have joined. Thank you!
