### ISSUE TITLE
3d mvc on S912

### ISSUE THREAD

**Issue by andresayang** [CoreELEC/CoreELEC#70]
Hi,

Id there any way to play full iso 3D mvc on amlogic S912 ?

Thanks

**Comment by gelotus** [comment]
What do you mean with full iso?

**Comment by andresayang** [comment]
"What do you mean with full iso?": Well, i mean playing bluray iso "3d". I think the format is called "h264 mvc", (well not sbs or tb in mkv ). Yes i think raspberry pi can do it.

**Comment by adamg88** [comment]
Will look into adding popcornmix patch into next release, it will not be until 8.90.3 though.

**Comment by adamg88** [comment]
This is not an issue/bug it is a feature request, it would be better suited moving this to our forums.
