### ISSUE TITLE
8.90.2 Noise in black bars

### ISSUE THREAD

**Issue by riegaz** [CoreELEC/CoreELEC#72]
Since the update there is noise visible in the black bars on the top and bottom of a movie while watching Live TV. Did not test other sources but I guess it is some recent change.

Any idea is welcome. Previous versions did not show this.

KI Plus S905

**Comment by boot2k3** [comment]
Didn't see any noise in black sections for IPTV
Try to activate "Disable noise reduction" if it still not activated.

**Comment by riegaz** [comment]
Seems only one channel is affected by this noise. All good.
