### ISSUE TITLE
HDHomeRunPVR Issue

### ISSUE THREAD

**Issue by KSears91** [CoreELEC/CoreELEC#73]
I am not sure if this issue belongs here, but I am getting no support on their forum. I just updated to release CoreELEC-Odroid_C2.arm-8.90.1 and I am now getting an error when I try and install zuki.pvr.hdhomerundvr-linux-armhf-leia-1.2.8.6572 repo. "kodi.binary.instance.pvr version 5.8.0 could not be satisfied." It was not doing this on the last version (CoreELEC-Odroid_C2.arm-8.90.0.tar) Any idea what is going on? It will also not work with the 8.90.2 release.

Link to Repo:

https://github.com/djp952/pvr.hdhomerundvr/releases/download/leia-1.2.8/zuki.pvr.hdhomerundvr-linux-armhf-leia-1.2.8.6572.zip

Link to Forum:

https://forum.silicondust.com/forum/viewtopic.php?f=88&t=65776&start=435

**Comment by adamg88** [comment]
Our PVR instance in 8.90.2 is 5.9.0 so it should work, would need logs to investigate further.

**Comment by Raybuntu** [comment]
This won't work. You are trying some third party pvr binary addon that was not compiled against the Kodi version we use. You need to ask your Addon maintainer to compile against latest Kodi master.
