### ISSUE TITLE
Deactivating 3D-mode after stopping a 3D-video does not work

### ISSUE THREAD

**Issue by pepeq2** [CoreELEC/CoreELEC#76]
3D-autoswitching works when starting a 3D-movie, TV switches to 3D-mode. But after stopping the 3D-movie the GUI stays in 3D-mode (3D-mode is not deactivated). The TV does not get the signal to deactivate the 3D-mode and there is also no info from the skin, that 3D-mode is deactivated. Automatic 3D-deactivation is set in Settings. When then a 2D-video is started, a message that no 3D-signal was found and the 3D-mode is deactivated.

**Comment by adamg88** [comment]
This is a Kodi bug not a CE bug.

**Comment by pepeq2** [comment]
ok, I will test with LE and forward the issue to the Kodi/LE forum.

**Comment by pepeq2** [comment]
understand, so I reopen the issue. Please feel free to close it again.

**Comment by afl1** [comment]
I fixed this common issue for kodi  by [kodi: register StereoscopicManager for message target](https://github.com/CoreELEC/CoreELEC/commit/0c189eb3d96c0e8d2349652487b8d7393369e09b).  In next CE release it'll be fixed. I created PR in xbmc for fixing 3D off issue.

**Comment by pepeq2** [comment]
works with devel version from 12.05.2018

**Comment by adamg88** [comment]
Thanks for reporting @pepeq2
