### ISSUE TITLE
Can't play certain mp4 files

### ISSUE THREAD

**Issue by newkind** [CoreELEC/CoreELEC#78]
I seem to have issues with playing certain mp4 files. I'm not sure what could be the issue here but mpv and VLC players on my computer are playing them fine. Looks like there is an issue with creating demuxer - can this be codec related issue ?

Codec details reported by VLC : 

![coreelec 2018-05-08 15-01-05](https://user-images.githubusercontent.com/1641534/39758672-d9cd33cc-52d0-11e8-8871-f95d87ed6a9c.jpg)

Let me just add that all of these problematic files are playing fine under Android 7.1 and Kodi 17.6

Here's log: https://pastebin.com/raw/SKmBex0t

**Comment by chatbuddy21** [comment]
Possibly Anime Hi10p files, unfortunately those files can't be hardware decoded. You can try using software decoder but I doubt it can handle those 1080p files. I don't think it can be fixed via CE since it requires a stronger cpu.

**Comment by newkind** [comment]
I don't think that's it. It's an old anime from 1983 so it certainly wouldn't benefit from Hi10p, also I got other Hi10p anime movie that plays, but it's a little bit sluggish - but still plays. This one does nothing. When you hit the play button - it tries to load it for a second and then nothing happens. It goes back to the episode list view. The other thing that I mentioned above is that these files do play just fine on my other S912 device - M8S Pro L and Kodi 17.6

Here is one of the episodes for test : https://mega.nz/#!slp00BrS!4cUFy4cJuMtVO62jDsvSu6E17GEGim4izEPV-DPGOTo

**Comment by newkind** [comment]
Ok so looks like it's confirmed as a bug in FFmpeg, so I'm closing this ticket :)
