### ISSUE TITLE
NETFLIX

### ISSUE THREAD

**Issue by satel11** [CoreELEC/CoreELEC#79]
Hi there,

help me please with installing NETFLIX. I downloaded the freshly NETFLIX [addon ](https://github.com/asciidisco/plugin.video.netflix/wiki/Installation) and install it, and "**An update of Widevine CDM is required to play this content**" intall too (from an 1.3GB Chrome OS recovery), but than the play with error stopped .
What should i do to make NETFLIX work (point by point)?

thank you

**Comment by Raybuntu** [comment]
You need to ask the add-on author's for support.

**Comment by adamg88** [comment]
There is instructions in our FAQ for widevine and Netflix. The issues system is for bugs, please use the forums for support related questions.
