### ISSUE TITLE
Latest devel release keeps freezing

### ISSUE THREAD

**Issue by wodgey** [CoreELEC/CoreELEC#8]
woke up this morning and it wouldn't respond to the remote keypresses. (Similar thing happened last night but i thought it might have been me trying to poke at things). We'd left an unfinished movie paused overnight.

Unfortunately, the Mrs pulled the power cable before  i could do any research, like testing ssh, top'ing, web interface etc.

When it happens again, what logs should i post? (Just .kodi/temp/kodi.log ??)

Ive got nexbox a1 s912 2g/16g. Using the dtb from 8.90.5 release

**Comment by wodgey** [comment]
Returned home to find the same thing had happened.

I can ssh into the box and top said the cpu was running at 200%.

Heres the log file
[kodi.log.txt](https://github.com/CoreELEC/CoreELEC/files/1910475/kodi.log.txt)

**Comment by HeresJonny** [comment]
That sounds more like a Kodi issue. Kodi does not handle resuming from sleep/powersave well.

**Comment by adamg88** [comment]
This is not a CoreELEC related issue but one related to my personal builds, if you still have issues when using a CE build when they are released then please feel free to reopen another issue.
