### ISSUE TITLE
odroid c2 clean install crashes when trying to navigate with phillips tv remote

### ISSUE THREAD

**Issue by maxodoble** [CoreELEC/CoreELEC#80]
Hi,

did a clean install of latest coreelec release (8.90.2) on my c2.

as soon as i try to navigate with my remote after booting up, coreelec crashes/shuts down.

i was able to ssh to the box, and did a journalctl -f and caught whats happening immediately after i pressed the first key on my remote (philips tv remote, hdmi-cec): see attached file.

if you need a debug log: need a hint how to enable debug log via ssh, because obviously enabling via remote wouldn't work ;-)

[log.txt](https://github.com/CoreELEC/CoreELEC/files/1984630/log.txt)

**Comment by Raybuntu** [comment]
There should be a Kodi crash log in .kodi/temp

**Comment by maxodoble** [comment]
yep. there was one, see attachement.

thanks
max

[kodi_crash.log](https://github.com/CoreELEC/CoreELEC/files/1984953/kodi_crash.log)

**Comment by adamg88** [comment]
Sorry for late response here but are you sure you have done a clean install properly? We have over 100 users with the C2 running without issue?

**Comment by maxodoble** [comment]
i did a clean install twice to be sure (used the le imge writer).

 issue seems to be with the hdmi-cec implementation and is happening when i try to navigate with my philps tv remote. didnt happen with raybuntus old leia testbuilds, but is present in all coreelec versions i tested for the c2.
issue isn't present when i use a logitec k400, just can't use the tv remote with hdmi-cec.

max

**Comment by adamg88** [comment]
we have a new version coming out soon with a new kernel, would you mind giving that a try when it is released

**Comment by maxodoble** [comment]
sure, will test/check when it's released.

thanks.

**Comment by MartB** [comment]
Works for me with a samsung remote and CEC not sure if that helps.

**Comment by maxodoble** [comment]
fyi:

problem still exists in 8.90.3 on the odroid c2.

seems to be a conflict of philips tv remote and the odroid built in ir-receiver, found a few messages about this problem in the forums.

problem can be solved with:
https://www.kodinerds.net/index.php/Thread/59020-Odroid-C2-IR-Empf%C3%A4nger-deaktivieren/?postID=418650#post418650

so this issue can be closed as far as i am concerned, for my usecases the mentionend fix is o.k. 

cheers,
Max
