### ISSUE TITLE
Le Potato: Network stack crash on huge file writes

### ISSUE THREAD

**Issue by studumpling** [CoreELEC/CoreELEC#81]
Issue it outlined and specified here:
https://forum.armbian.com/topic/6591-le-potato-network-stack-crash-on-huge-file-writes/

Looking over the commits, I thought I saw the kernel get updated, but maybe I'm reading it wrong, as I've still got this issue on the 8.90.2 release. Just wanted to get a ticket open on it so I know when the issue itself is resolved, as it's keeping me on my RPi until it's fixed.

**Comment by adamg88** [comment]
Let us know if this issue exists after 8.90.3 and we can look into it more as we are changing to a different kernel with this release.

**Comment by cata747** [comment]
WIth the latest devel Le Potato still freezes after a while.

**Comment by oz-ra** [comment]
@adamg88 Thanks.

I am experiencing the same. Definitely OS based from what I can tell.
Limited to Le Potato S905X and does not affect the Odroid C2.

I have tried the below so far for Le Potato and will wait for your 8.90.3 to test.
CoreELEC 8.90.2 release
CoreELEC 8.90.1 release
CoreELEC 8.90.0 release

Thanks for all your hard work.

http://forum.loverpi.com/discussion/comment/712#Comment_712
