### ISSUE TITLE
Khadas VIM2: "401" from TMDB and some other issues

### ISSUE THREAD

**Issue by TheSwede86** [CoreELEC/CoreELEC#82]
Board: Khadas VIM2 Pro (3GB)
Used device tree: gxm_q200_3g.dtb (as "dtb.img")
Release: 8.90.2

Hiya,

Unsure if this is an actual "issue" worth posting here but I think this is not on my end so here it goes.
Link pastebin from kodi.log (sanitized and cropped):
https://pastebin.com/MBjJ1N9f

1) On row 1 it seems to complain about "temporary failure in name resolution" but I am able to successfully resolve DNS-entries as "proven" by the second error I get when trying to scrape my library using TMDB

2) On row 32-33 I seem to get "401" i.e. "Unauthorized" from TMDB when trying to get info for a movie, is there something wrong with the API-key or anything like that?
Trying the actual URL in my browser I get this response:
"{"status_code":7,"status_message":"Invalid API key: You must be granted a valid key.","success":false}"

Thanks a bunch your your time and assistance - TheSwede86

**Comment by adamg88** [comment]
Your first problem is as a result of your box not getting an IP from your network quick enough before all the services have started.

Your second problem is a problem is an upstream issue and not something we are responsible for.
