### ISSUE TITLE
Subtitles break smooth; KVIM2, Amlogic S912, 24Hz;

### ISSUE THREAD

**Issue by nemoforum** [CoreELEC/CoreELEC#83]
When playing 24 Hz movie with subtitles enabled, text appearing/disappearing produces small lags/freezes.
There is no issues if subtitles are disabled.
Refresh rate automatically switched to 24 Hz on playback start and get back to 60 Hz on playback stop.

Tested on KVIM2, Amlogic S912, CoreELEC 8.90.0 and CoreELEC 8.90.2.

**Comment by chatbuddy21** [comment]
have you already disable dirty regions?

**Comment by afl1** [comment]
This issue will be fixed in next build by disabling dirty regions [kodi: advancedsettings.xml disable Dirty Regions completely to fix Subtitles - video playback stuttering on S912's](https://github.com/CoreELEC/CoreELEC/commit/24dc645c452832cad2eb73738117db3f09764475).
