### ISSUE TITLE
Which release file for wetek play 2?

### ISSUE THREAD

**Issue by tuxedo0801** [CoreELEC/CoreELEC#9]
Hey, this is not a big issue, but it's totally unclear to me: 

Which release download image do I need for wetek play 2?

On earlier raybuntu LE releases, there was always a wetek play 2 version. Now there is none. I guess one of those S905 will work?

br,
Alex

P.S. Device tree is also not clear to me. Found the repo: https://github.com/CoreELEC/device-trees-amlogic
But which one is for wetek play 2? This one seems to fit best, right? --> gxbb_p200_1G_1Gbit_RealtekWiFi.dts

**Comment by adamg88** [comment]
You use the S905 image, please ignore the repo as it is for building from source purposes only.

There is a specific wetek play 2 dtb, when you burn the img.gz to a USB or sdcard you will see it in the device_trees folder at the root of the device.

Copy this dtb to ROOT:/dtb.img

We will put some information on the website to help users like yourself in the future, if you need further help then open a fresh ticket, thanks.

**Comment by tuxedo0801** [comment]
Thanks for the fast response. I will try ..

**Comment by tuxedo0801** [comment]
Works for wetek play 2 ...thanks.
