### ISSUE TITLE
[S905x] Moonlight is broken

### ISSUE THREAD

**Issue by nextlooper42** [CoreELEC/CoreELEC#90]
Hi,

Moonlight addon won't install completely because it still wants os.libreelec.tv repo. It installs script for Moonlight but not Moonlight Embedded because of this. This "error" can occur with many addons in your CoreELEC repo. Kinda game breaking bug :D

Please add libreelec repo back or fix it somehow ASAP.

**Comment by adamg88** [comment]
Its already there this is a Kodi related bug, if you press ok the install will continue as normal.

**Comment by nextlooper42** [comment]
Yes, app install itself. But when you execute Moonlight from addon menu it gives an error...

**Comment by adamg88** [comment]
Ok well that is rather vague, no log, no help

**Comment by nextlooper42** [comment]
Well, this is log from clean installation. Btw thanks
[kodi_moonlighterror.log](https://github.com/CoreELEC/CoreELEC/files/1998820/kodi_moonlighterror.log)
