### ISSUE TITLE
 The volume control of the Wetek Play 2 remote control does not work anymore

### ISSUE THREAD

**Issue by Coolzero82** [CoreELEC/CoreELEC#93]
Since the update to CE 8.90.2, the volume button of the Wetek Play 2 remote control has stopped working, while pressing volume plus or minus displays the volume icon on the TV, but it does not get louder or softer. Enclosed the Kodi Log
[kodi.log.TV.zip](https://github.com/CoreELEC/CoreELEC/files/2010175/kodi.log.TV.zip)

**Comment by afl1** [comment]
You audio 6ch AC3 is passthrough. You can't set volume in tv box.

**Comment by Coolzero82** [comment]
OK, you're right, if I disabled passthrough, everything looks fine, thanks
