### ISSUE TITLE
Between film / series and advertising short sound misfire

### ISSUE THREAD

**Issue by Coolzero82** [CoreELEC/CoreELEC#94]
Since CE 8.90.2 I have had short sound skip on the Wetek Play 2 between movies / series and the starting commercial, which was not the case under CE 8.90.1. Enclosed the log
[kodi.log.TV.zip](https://github.com/CoreELEC/CoreELEC/files/2010179/kodi.log.TV.zip)

**Comment by adamg88** [comment]
Fixed in the upcoming release 8.90.3.
