### ISSUE TITLE
 Skin.helper error, Rapier

### ISSUE THREAD

**Issue by Coolzero82** [CoreELEC/CoreELEC#95]
I use the Rapier skin under CE 8.90.2 and get a "Skin Helper Error" at the Kodi start, in the log I find this:
`07:18:02.027 T:3654169456   DEBUG: Previous line repeats 287 times.
07:18:02.027 T:3654169456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'utf8' codec can't decode byte 0xfc in position 35: invalid start byte
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.skin.helper.backgrounds/service.py", line 10, in <module>
                                                BackgroundsUpdater().run()
                                              File "/storage/.kodi/addons/script.skin.helper.backgrounds/resources/lib/backgrounds_updater.py", line 95, in run
                                                self.update_backgrounds()
                                              File "/storage/.kodi/addons/script.skin.helper.backgrounds/resources/lib/backgrounds_updater.py", line 394, in update_backgrounds
                                                "SkinHelper.AllMusicSongsBackground", "musicdb://songs/", label=32022)
                                              File "/storage/.kodi/addons/script.skin.helper.backgrounds/resources/lib/backgrounds_updater.py", line 276, in set_background
                                                images = self.get_images_from_vfspath(lib_path)
                                              File "/storage/.kodi/addons/script.skin.helper.backgrounds/resources/lib/backgrounds_updater.py", line 200, in get_images_from_vfspath
                                                image["thumbnail"] = get_clean_image(media["thumbnail"])
                                              File "/storage/.kodi/addons/script.module.metadatautils/lib/metadatautils.py", line 318, in get_clean_image
                                                return _get_clean_image(*args, **kwargs)
                                              File "/storage/.kodi/addons/script.module.metadatautils/lib/helpers/utils.py", line 161, in get_clean_image
                                                image = image.decode("utf8")
                                              File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 35: invalid start byte
                                            -->End of Python script error report<--
07:18:02.028 T:4094980672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
07:18:02.029 T:4094980672   DEBUG: Previous line repeats 9 times.
07:18:02.029 T:4094980672   DEBUG: ------ Window Init (DialogNotification.xml) ------
07:18:02.032 T:4094980672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
07:18:02.244 T:4017857392   DEBUG: Previous line repeats 134 times.
07:18:02.245 T:4017857392   DEBUG: LIRC: - NEW 6a 0 KEY_RIGHT devinput (KEY_RIGHT)
07:18:02.245 T:4094980672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
07:18:02.246 T:4094980672   DEBUG: Previous line repeats 7 times.
07:18:02.246 T:4094980672   DEBUG: HandleKey: 168 (0xa8, obc87) pressed, action is Right
07:18:02.250 T:4094980672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
07:18:02.281 T:3935286128   DEBUG: Previous line repeats 21 times.
07:18:02.282 T:3935286128   DEBUG: ffmpeg[EA8FB370]: Invalid return value 0 for stream protocol
07:18:02.283 T:4094980672   DEBUG: Previous line repeats 1 times.
07:18:02.283 T:4094980672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
07:18:02.354 T:3935286128   DEBUG: Previous line repeats 44 times.
07:18:02.354 T:3935286128   DEBUG: ffmpeg[EA8FB370]: [swscaler] No accelerated colorspace conversion found from yuv420p to bgra.
07:18:02.362 T:4094980672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
07:18:02.364 T:3654169456   DEBUG: Previous line repeats 9 times.
07:18:02.364 T:3654169456   DEBUG: Skin Helper Simplecache --> Closed
07:18:02.368 T:4094980672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
07:18:02.380 T:3935286128   DEBUG: Previous line repeats 10 times.
07:18:02.380 T:3935286128   DEBUG: DoWork - took 132 ms to load special://masterprofile/Thumbnails/2/21abdb39.jpg
07:18:02.384 T:4094980672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
07:18:02.394 T:4094980672   DEBUG: Previous line repeats 1 times.
07:18:02.394 T:4094980672   DEBUG: GLES: Extension Support Test - GL_EXT_texture_format_BGRA8888 YES
07:18:02.432 T:4094980672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
07:18:02.500 T:3654169456   DEBUG: Previous line repeats 79 times.
07:18:02.500 T:3654169456    INFO: Python script stopped
07:18:02.500 T:3654169456   DEBUG: Thread LanguageInvoker 3654169456 terminating
07:18:02.503 T:4094980672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
07:18:02.514 T:4094980672   DEBUG: Previous line repeats 9 times.
07:18:02.514 T:4094980672   DEBUG: GLES: Extension Support Test - GL_EXT_texture_format_BGRA8888 YES
07:18:02.514 T:4094980672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
07:18:02.514 T:4094980672   DEBUG: GLES: Extension Support Test - GL_EXT_texture_format_BGRA8888 YES
07:18:02.515 T:4094980672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
07:18:05.101 T:3408917360   DEBUG: Previous line repeats 1247 times.
07:18:05.101 T:3408917360   DEBUG: Skin Helper Service --> Ended Background worker...
07:18:05.112 T:4094980672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
07:18:08.431 T:4094980672   DEBUG: Previous line repeats 1594 times.
07:18:08.432 T:4094980672   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
07:18:08.438 T:4094980672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.`

The entire log is attached
[kodi.log.Amazon.zip](https://github.com/CoreELEC/CoreELEC/files/2010195/kodi.log.Amazon.zip)

**Comment by adamg88** [comment]
This is an issue with the add-on script.skin.helper.backgrounds

You will need to contact the add-on developer.
