### ISSUE TITLE
Le Potato: Switching to > 1080p with framerate > 24Hz -> black screen

### ISSUE THREAD

**Issue by antoinelochet** [CoreELEC/CoreELEC#97]
Hello,

I wanted to test 8.90.2 on my Le Potato to see the IR improvements (which seem OK by the way).
When switching to 4K@60Hz, I ended up getting a black screen.
I have meddled a bit and found out that neither 3840*2160p nor 4096*2160p work above 24Hz.
It works fine with other distros and I think, even in 8.90.1

**Comment by arthur-liberman** [comment]
What TV do you have? And do you have HDMI 2.0 enabled on the HDMI port the Le Potato is connected to?
It's much more likely that the TV does not accept the signal than a CE problem.
